/* Device-local course app. Authored course data is read-only; no account required. */
(function(){'use strict';
const $=s=>document.querySelector(s), M=window.TensegrityModels, KEY='tensegrity.learn.v2';
let course=null,state,installEvent=null,offlineReady=false,pendingImport=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaultState=()=>({schema:1,route:'solar-builder',font:'normal',completed:{},notes:{},quiz:{},lastLesson:1});
function validateState(raw){
 if(!raw||raw.schema!==1||!['solar-builder','community-facilitator','prototype-technician','robotics','research','full-core'].includes(raw.route)||!['normal','large'].includes(raw.font))throw Error('This is not a supported progress backup');
 let clean=defaultState();clean.route=raw.route;clean.font=raw.font;
 for(const key of ['completed','notes','quiz']){
  if(!raw[key]||typeof raw[key]!=='object'||Array.isArray(raw[key]))throw Error('Missing '+key+' records');
  for(const [id,value] of Object.entries(raw[key])){
   if(!/^\d+$/.test(id)||+id<1||+id>48)throw Error('Invalid lesson ID');
   if(key==='notes'){if(typeof value!=='string'||value.length>10000)throw Error('Invalid note');clean.notes[id]=value;}
   if(key==='completed'){if(typeof value!=='string'||value.length>100||!Number.isFinite(Date.parse(value)))throw Error('Invalid review date');clean.completed[id]=value;}
   if(key==='quiz'){if(!Number.isInteger(value)||value<0||value>2)throw Error('Invalid quiz answer');clean.quiz[id]=value;}
  }
 }
 if(Number.isInteger(raw.lastLesson)&&raw.lastLesson>=1&&raw.lastLesson<=48)clean.lastLesson=raw.lastLesson;
 return clean;
}
function announce(text){const n=$('#notice');n.textContent=text;n.hidden=false;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){announce('This device could not save progress. Export a backup before closing the app.');return false;}}
function phaseName(p){return course.phases.find(x=>x.id===p)?.title??'';}
function lesson(id){return course.lessons.find(x=>x.id===+id);}
function routeLessons(){return course.lessons.filter(l=>course.routes[state.route].includes(l.phase));}
function reviewed(list=course.lessons){return list.filter(l=>state.completed[l.id]).length;}
function nextLesson(){let list=routeLessons();return list.find(l=>!state.completed[l.id])||lesson(state.lastLesson)||list[0];}
function para(t){return '<p>'+esc(t)+'</p>';}
function checklist(items){return '<ol>'+items.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ol>';}
function section(title,body,open=false){return '<details class="lesson-section"'+(open?' open':'')+'><summary>'+esc(title)+'</summary><div class="section-body">'+body+'</div></details>';}
function phaseHtml(p,items){let done=reviewed(items);return '<details class="phase"'+(p===nextLesson().phase?' open':'')+'><summary><span class="phase-number">'+String(p).padStart(2,'0')+'</span><span class="phase-heading">'+esc(phaseName(p))+'<span class="phase-meta">'+done+' of '+items.length+' reviewed</span></span></summary><div class="lesson-list">'+items.map(l=>'<a class="lesson-link" href="#lesson/'+l.id+'"><span class="lesson-number">'+String(l.id).padStart(2,'0')+'</span><span>'+esc(l.title)+'</span><span class="lesson-status">'+(state.completed[l.id]?'Reviewed':'')+'</span></a>').join('')+'</div></details>';}
function learn(){const list=routeLessons(),next=nextLesson(),done=reviewed(list);return '<p class="eyebrow">Your learning path</p><h1 class="page-title">Build understanding, one lesson at a time.</h1><p class="muted">'+done+' of '+list.length+' lessons reviewed on this device</p><section class="card next-card"><div><p class="eyebrow">'+(done===list.length?'Keep exploring':'Your next lesson')+'</p><h2>'+esc(next.title)+'</h2><p class="muted small">Lesson '+String(next.id).padStart(2,'0')+' · '+esc(phaseName(next.phase))+'</p><a class="primary" href="#lesson/'+next.id+'" style="display:inline-block;text-decoration:none">'+(done===list.length?'Open lesson':'Continue learning')+'</a></div><img class="prism-small" src="./assets/prism.svg" alt="Labeled three-strut prism"></section><div class="search-row"><div><label for="course-search">Find a lesson</label><input id="course-search" type="search" placeholder="Solar, forces, community…"></div><div><label for="route">Learning path</label><select id="route">'+Object.entries(course.routeNames).map(([key,name])=>'<option value="'+key+'"'+(state.route===key?' selected':'')+'>'+esc(name)+'</option>').join('')+'</select></div></div><p id="search-count" class="small muted">'+list.length+' lessons in this path</p><div id="phase-list">'+course.phases.filter(p=>course.routes[state.route].includes(p.id)).map(p=>phaseHtml(p.id,list.filter(l=>l.phase===p.id))).join('')+'</div><footer class="legal">Review is self-reported. Keep practical evidence and use the course rubric; quiz answers alone do not validate a physical build.</footer>';}
function lessonView(id){const l=lesson(id);if(!l)return '<h1>Lesson not found</h1><a href="#learn">Return to your course</a>';state.lastLesson=l.id;save();let selected=state.quiz[l.id];const q=l.mobileQuiz;
 const quiz='<p>'+esc(q.question)+'</p><div role="group" aria-label="Quiz answers">'+q.options.map((v,i)=>'<button class="quiz-option" type="button" data-quiz="'+i+'" data-lesson="'+l.id+'" aria-pressed="'+(selected===i)+'">'+esc(v)+'</button>').join('')+'</div><div id="quiz-feedback" aria-live="polite">'+(selected===undefined?'':feedback(l,selected))+'</div><details><summary>Three teach-back questions</summary>'+l.questions.map((question,i)=>'<h3>'+esc(question)+'</h3>'+para(l.answers[i])).join('')+'</details>';
 return '<div class="lesson-view"><a class="back" href="#learn">Back to your learning path</a><div class="lesson-heading"><p class="eyebrow">Phase '+String(l.phase).padStart(2,'0')+' · Lesson '+String(l.id).padStart(2,'0')+'</p><h1 class="page-title">'+esc(l.title)+'</h1><p class="muted">'+esc(l.objective)+'</p><span class="chip">'+esc(phaseName(l.phase))+'</span>'+(state.completed[l.id]?'<span class="chip">Reviewed</span>':'')+'</div>'+section('Understand the idea',para(l.concept)+'<img class="diagram" src="./assets/prism.svg" alt="Prism reference: blue tension cables, thick red compression struts, labeled nodes">',true)+section('Worked example',para(l.worked))+section('Try it', '<h3>Materials and setup</h3>'+para(l.materials)+'<h3>Predict before you begin</h3><p>Write what you expect, then follow the steps. Keep a mismatch as evidence.</p>'+checklist(l.steps)+(l.lab?'<a class="download-link" href="#labs/'+l.lab+'">Open the '+esc(l.lab)+' lab</a>':'')+'<h3>Expected behavior</h3>'+para(l.expected)+'<div class="note">'+esc(l.pitfall)+'</div>')+section('Check your understanding',quiz,selected!==undefined)+section('Your evidence and notes',para(l.artifact)+'<label for="lesson-note">Private note on this device</label><textarea id="lesson-note" maxlength="10000" data-lesson="'+l.id+'" placeholder="Prediction, measurements, units, what surprised you…">'+esc(state.notes[l.id]||'')+'</textarea><p id="note-saved" class="saved-label" aria-live="polite"></p><p class="small muted">Label calculations and example data clearly. Do not claim an experiment you have not performed.</p>',false)+'<div class="card lesson-footer"><p><b>'+ (state.completed[l.id]?'You marked this lesson reviewed.':'Ready to record your review?')+'</b></p><p class="small muted">Use this after explaining the idea and recording the relevant evidence. This is your own progress record, not a qualification.</p><button class="primary" type="button" data-review="'+l.id+'">'+(state.completed[l.id]?'Undo reviewed status':'Mark lesson reviewed')+'</button></div><div class="two-buttons">'+(l.id>1?'<a class="secondary" href="#lesson/'+(l.id-1)+'" style="text-align:center;text-decoration:none">Previous lesson</a>':'')+(l.id<48?'<a class="secondary" href="#lesson/'+(l.id+1)+'" style="text-align:center;text-decoration:none">Next lesson</a>':'')+'</div></div>';
}
function feedback(l,index){let correct=index===l.mobileQuiz.correct;return '<div class="feedback'+(correct?'':' wrong')+'"><b>'+(correct?'Correct.':'Try again.')+'</b> '+esc(l.mobileQuiz.explanation)+'</div>';}
function progress(){const list=routeLessons(),done=reviewed(list),quizDone=course.lessons.filter(l=>state.quiz[l.id]===l.mobileQuiz.correct).length;return '<p class="eyebrow">Your progress</p><h1 class="page-title">Keep the evidence with the learning.</h1><p class="muted">Stored on this device. Export a backup to move to another phone.</p><div class="grid"><section class="card"><div class="metric-row"><div><p class="small muted">Selected learning path</p><div class="metric">'+done+' / '+list.length+'</div></div><div><p class="small muted">Whole course</p><div class="metric">'+reviewed()+' / 48</div></div></div><div class="progress-track" role="progressbar" aria-label="Reviewed lessons in selected path" aria-valuenow="'+done+'" aria-valuemin="0" aria-valuemax="'+list.length+'"><div class="progress-fill" style="width:'+(done/list.length*100)+'%"></div></div><p class="small muted">Reviewed lessons are self-reported; '+quizDone+' knowledge checks answered correctly.</p></section><section class="card"><h2>Your notebook backup</h2><p>Save your reviewed lessons, quiz answers and private notes as a file.</p><div class="actions"><button class="primary" type="button" data-export>Export progress</button><label class="secondary" style="margin:0;cursor:pointer">Import backup<input id="import-file" type="file" accept="application/json,.json" style="display:none"></label></div><div id="import-review" aria-live="polite"></div></section></div><h2 style="margin-top:26px">Reviewed lessons</h2><div class="card" style="padding:0">'+(reviewed()?course.lessons.filter(l=>state.completed[l.id]).map(l=>'<a class="lesson-link" href="#lesson/'+l.id+'"><span class="lesson-number">'+String(l.id).padStart(2,'0')+'</span><span>'+esc(l.title)+'</span><span class="lesson-status">Reviewed</span></a>').join(''):'<div class="empty">Your first review will appear here. <a href="#lesson/1">Open lesson 01</a>.</div>')+'</div><footer class="legal">Clearing browser data can remove progress and offline content. Keep a backup. No cloud synchronization or accredited certificate is provided.</footer>';}
function settings(){return '<p class="eyebrow">Your app</p><h1 class="page-title">Learn at your own pace.</h1><div class="grid"><section class="card"><h2>Reading and installation</h2><label for="font-size">Text size</label><select id="font-size"><option value="normal"'+(state.font==='normal'?' selected':'')+'>Standard</option><option value="large"'+(state.font==='large'?' selected':'')+'>Larger</option></select><div class="settings-row"><button class="primary" type="button" data-install>Install on your phone</button></div><span id="offline-status" class="offline-badge">'+(offlineReady?'Ready offline':'Checking offline download…')+'</span><p class="small muted" style="margin-top:12px">After the first full download, course content and labs work offline while the device retains its cache. External reference links need a connection.</p></section><section class="card"><h2>About this course</h2><p>48 practical tensegrity lessons for solar concepts, community learning and evidence-based exploration.</p><p>Lessons are in English. A Chinese getting-started guide and bilingual glossary are included.</p><div class="links-row"><a href="./resources/START_HERE_ZH.md" download>中文入门指南</a><a href="./resources/GLOSSARY.md" download>English–Chinese glossary</a></div><p class="small muted" style="margin-top:15px">Version 2.0 · Course by Ivan and Tensegrity from Scratch contributors · MIT license.</p><a href="https://github.com/freedomyamato/tensegrity-from-scratch" target="_blank" rel="noopener">Source and full teaching repository</a></section></div><section class="card" style="margin-top:20px"><h2>Templates for your evidence</h2><div class="links-row">'+course.resources.map(r=>'<a href="./resources/'+esc(r.file)+'" download>'+esc(r.title)+'</a>').join('')+'</div></section><section class="card"><h2>Learning boundaries</h2><p>These labs are teaching models. Numerical equilibrium is not proof of stability or load capacity. Physical builds and teaching activities require appropriate pilot testing.</p><p>Full-size roofs, floating arrays and public structures need qualified site-specific review. Quantum Tensegrity remains an optional research hypothesis.</p><p class="small muted">Your notes, quiz choices and reviewed lessons stay in this browser’s local storage. This app has no learning account, analytics or server-side notebook. The hosting service may process normal access logs.</p></section>';}
const LAB_NAMES={prism:'Prism',sweep:'Twist sweep',spring:'Cable spring',buckling:'Buckling',oscillator:'Vibration',solar:'Solar energy',controller:'Mock control'};
function range(id,label,value,min,max,step=1,unit=''){return '<div class="field"><label for="'+id+'">'+label+' <output class="value" id="'+id+'-value">'+value+' '+unit+'</output></label><input type="range" id="'+id+'" value="'+value+'" min="'+min+'" max="'+max+'" step="'+step+'" data-unit="'+unit+'"></div>';}
function number(id,label,value,step='any'){return '<div class="field"><label for="'+id+'">'+label+'</label><input type="number" id="'+id+'" value="'+value+'" step="'+step+'" inputmode="decimal"></div>';}
function labFields(name){switch(name){
 case 'prism':return range('radius','Radius',80,40,160,1,'mm')+range('height','Height',140,60,240,1,'mm')+range('twist','Top-triangle twist',30,0,60,1,'°');
 case 'sweep':return '<p>Hold radius at 80 mm and height at 140 mm. Compare nine twist angles against the same reference self-stress.</p><p class="small muted">This is a constrained scan, not a general form-finding solver.</p>';
 case 'spring':return number('k','Stiffness k (N/m)',100)+number('length','Current length (mm)',150)+number('rest','Rest length (mm)',140);
 case 'buckling':return number('E','Illustrative modulus E (Pa)',2000000000)+number('I','Second moment I (m⁴)',1e-10)+number('L','Length (mm)',200)+number('K','Effective length factor K',1);
 case 'oscillator':return range('damping','Damping c',.4,0,2,.1,'N·s/m')+range('stiffness','Stiffness k',4,1,20,1,'N/m')+'<p class="small muted">Mass 1 kg · initial displacement 10 mm · one degree of freedom · 5 seconds.</p>';
 case 'solar':return '<label for="solar-csv">Simultaneous loaded readings</label><textarea id="solar-csv" spellcheck="false" style="font-family:monospace;font-size:.875rem">time_s,voltage_V,current_A\n0,5,0.1\n60,5,0.12\n120,5,0.1</textarea><p class="small muted" style="margin-top:12px">The starting values are synthetic. Enter your own timestamped loaded V and I readings; do not combine open-circuit V and short-circuit I.</p><button class="primary" type="button" data-calculate>Calculate energy</button>';
 case 'controller':return range('target','Target length',160,120,180,1,'mm')+range('gain','Proportional gain',.2,.05,.5,.05)+'<p class="small muted">Starts at 150 mm · maximum step 1 mm · command limits 120–180 mm.</p>';
 }}
function labs(name='prism'){if(!LAB_NAMES[name])name='prism';return '<p class="eyebrow">Interactive labs</p><h1 class="page-title">Change a parameter. See what follows.</h1><p class="muted">Calculations run on your phone. No Python installation needed.</p><div class="lab-tabs" role="group" aria-label="Choose a lab">'+Object.entries(LAB_NAMES).map(([key,label])=>'<button class="lab-tab" data-lab="'+key+'" aria-pressed="'+(name===key)+'" type="button">'+label+'</button>').join('')+'</div><div class="lab-layout"><section class="card" id="lab-controls" data-active-lab="'+name+'"><h2>'+LAB_NAMES[name]+'</h2>'+labFields(name)+'</section><section id="lab-result" aria-live="polite"></section></div><footer class="legal">Educational idealizations, not a structural certification or a hardware controller.</footer>';}
function table(headers,rows){return '<div class="table-wrap"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function prismSvg(result){let n=result.nodes,s=800,points=n.map(([x,y,z])=>[220+s*(x-.45*y),260-s*(z+.28*y)]),lines=result.members.map(m=>{let a=points[m.a],b=points[m.b];return '<line x1="'+a[0]+'" y1="'+a[1]+'" x2="'+b[0]+'" y2="'+b[1]+'" stroke="'+(m.kind==='strut'?'#cc403b':'#1764bb')+'" stroke-width="'+(m.kind==='strut'?7:2.5)+'"'+(m.name.startsWith('C')?' stroke-dasharray="5 4"':'')+'/>';}).join('');return '<svg class="lab-svg" viewBox="0 0 440 310" role="img" aria-label="Projected tensegrity prism. Blue cables, red struts. Node labels 0 to 5.">'+lines+points.map(([x,y],i)=>'<circle cx="'+x+'" cy="'+y+'" r="5" fill="white" stroke="#0d2035"/><text x="'+(x+10)+'" y="'+(y+4)+'" font-size="15" fill="#0d2035">'+i+'</text>').join('')+'</svg>';}
function chart(rows,yName='x',scale=1000,yLabel='Displacement (mm)'){let values=rows.map(r=>r[yName]*scale),max=Math.max(...values),min=Math.min(...values),span=max-min||1,end=rows[rows.length-1].time||1;let points=rows.map((r,i)=>(40+350*r.time/end).toFixed(2)+','+(220-160*(values[i]-min)/span).toFixed(2)).join(' ');return '<svg class="lab-svg" viewBox="0 0 440 270" role="img" aria-label="'+esc(yLabel)+' over time"><path d="M40 50 V220 H390" fill="none" stroke="#7890a5"/><polyline points="'+points+'" fill="none" stroke="#1263c4" stroke-width="2.5"/><text x="42" y="25" font-size="14">'+esc(yLabel)+'</text><text x="12" y="64" font-size="12">'+max.toFixed(1)+'</text><text x="12" y="222" font-size="12">'+min.toFixed(1)+'</text><text x="40" y="249" font-size="13">0</text><text x="325" y="249" font-size="13">'+end.toFixed(1)+' '+(yName==='reading'?'steps':'s / steps')+'</text></svg>';}
function resultMetric(value,label){return '<div class="output-card"><p class="small muted">'+esc(label)+'</p><div class="metric">'+esc(value)+'</div></div>';}
function calculateLab(){let controls=$('#lab-controls');if(!controls)return;let name=controls.dataset.activeLab;const v=id=>Number($('#'+id).value);let out='';
 try{switch(name){
 case 'prism':{let r=M.prism(v('radius')/1000,v('height')/1000,v('twist'));out=prismSvg(r)+resultMetric(r.nullity+'','Self-stress nullspace dimension')+table(['Family','Span (mm)'],[['Ring', (r.members[0].length*1000).toFixed(3)],['Cross cable',(r.members[6].length*1000).toFixed(3)],['Strut',(r.members[9].length*1000).toFixed(3)]])+'<div class="note">'+(r.residual<1e-10?'The reference self-stress balances. This does not establish stability or load capacity.':'The 30° reference self-stress does not balance at this twist. This rendering is geometry, not a valid equilibrium design.')+'</div><p class="small muted">Reference residual: '+r.residual.toExponential(2)+' N. Projection is not a cutting plan.</p>';break;}
 case 'sweep':{let rows=[0,15,25,29,30,31,35,45,60].map(a=>{let r=M.prism(.08,.14,a);return [a+'°',r.nullity,r.residual.toExponential(3)+' N'];});out='<section class="card"><h2>Twist comparison</h2>'+table(['Twist','Nullspace','Reference residual'],rows)+'<div class="note">The special 30° state has a nonzero self-stress. The scan does not prove stability or exhaust all possible geometries.</div></section>';break;}
 case 'spring':{let f=M.spring(v('k'),v('length')/1000,v('rest')/1000);out=resultMetric(f.toFixed(4)+' N','Cable tension')+'<section class="card"><h2>'+ (f===0?'The cable is slack in this model.':'The cable is carrying tension.')+'</h2><p>F = k × max(0, L − L₀)</p><p class="muted">The ideal cable cannot push. Real cords and joints may show creep, slip and nonlinear response.</p></section>';break;}
 case 'buckling':{let f=M.buckling(v('E'),v('I'),v('L')/1000,v('K'));out=resultMetric(f.toFixed(3)+' N','Ideal Euler critical load')+'<section class="card"><p>Pcr = π²EI / (KL)²</p><div class="note">Hypothetical inputs and ideal end conditions. This is not the safe load of a craft stick or a structural design approval.</div><p>Try doubling the length: the ideal load becomes one quarter.</p></section>';break;}
 case 'oscillator':{let rows=M.oscillator(1,v('stiffness'),v('damping'));out=chart(rows)+resultMetric(rows[rows.length-1].energy.toExponential(4)+' J','Mechanical energy at 5 seconds')+'<section class="card"><p>m ẍ + c ẋ + kx = 0</p><p class="muted">At zero damping, energy stays approximately constant. Positive damping dissipates energy. This is one oscillator, not a full tensegrity simulation.</p></section>';break;}
 case 'solar':{let rows=M.parseSolar($('#solar-csv').value),e=M.energy(rows);out=resultMetric(e.toFixed(6)+' Wh','Energy over the entered interval')+'<section class="card"><p>'+rows.length+' readings · '+(rows[rows.length-1].time_s-rows[0].time_s)+' seconds</p>'+table(['Time (s)','Power (W)'],rows.slice(0,30).map(r=>[r.time_s,(r.voltage_V*r.current_A).toFixed(4)]))+'<div class="note">P = loaded V × I. Energy uses trapezoidal integration. This does not measure conversion efficiency or remove differences in weather.</div></section>';break;}
 case 'controller':{let rows=M.controller(v('target')/1000,v('gain'));out=chart(rows,'x',1000,'Commanded length (mm)')+resultMetric((rows[rows.length-1].x*1000).toFixed(3)+' mm','Command after 20 mock steps')+'<section class="card">'+table(['Step','Reading (mm)','Next command (mm)'],rows.slice(0,6).map(r=>[r.time,(r.reading*1000).toFixed(3),(r.x*1000).toFixed(3)]))+'<div class="note">Mock plant only: the reading equals the command. No motors or force limits are connected. Do not use this controller on hardware.</div></section>';break;}
 }
 }catch(e){out='<section class="card"><h2>Check your inputs</h2><p role="alert">'+esc(e.message)+'</p></section>';}
 $('#lab-result').innerHTML=out;
}
function render(){if(!course)return;let hash=location.hash.slice(1)||'learn',[page,arg]=hash.split('/');let main=$('#main');if(page==='lesson')main.innerHTML=lessonView(+arg);else if(page==='labs')main.innerHTML=labs(arg);else if(page==='progress')main.innerHTML=progress();else if(page==='settings')main.innerHTML=settings();else{page='learn';main.innerHTML=learn();}
 document.documentElement.style.setProperty('--scale',state.font==='large'?'1.18':'1');document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===(page==='lesson'?'learn':page))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});if(page==='labs')calculateLab();document.title=(page==='lesson'&&lesson(+arg)?lesson(+arg).title+' · ':'')+'Tensegrity Learn';}
function download(name,text,type){let url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function showInstall(){if(installEvent){let event=installEvent;installEvent=null;event.prompt();event.userChoice.catch(()=>{});}else $('#install-dialog').showModal();}
function getOfflineStatus(){if(!navigator.serviceWorker?.controller)return;let ch=new MessageChannel();ch.port1.onmessage=e=>{offlineReady=e.data?.ready===true;const badge=$('#offline-status');if(badge)badge.textContent=offlineReady?'Ready offline':'Offline download is not complete';};navigator.serviceWorker.controller.postMessage({type:'OFFLINE_STATUS'},[ch.port2]);}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-close-dialog'))$('#install-dialog').close();
 if(b.id==='install-button'||b.hasAttribute('data-install'))showInstall();
 if(b.dataset.quiz!==undefined){let l=lesson(+b.dataset.lesson),index=+b.dataset.quiz;if(!l||!Number.isInteger(index)||index<0||index>2)return;state.quiz[l.id]=index;save();document.querySelectorAll('[data-quiz]').forEach(x=>x.setAttribute('aria-pressed',x===b?'true':'false'));$('#quiz-feedback').innerHTML=feedback(l,index);}
 if(b.dataset.review){let id=+b.dataset.review;if(!lesson(id))return;if(state.completed[id])delete state.completed[id];else state.completed[id]=new Date().toISOString();save();render();}
 if(b.dataset.lab)location.hash='labs/'+b.dataset.lab;
 if(b.hasAttribute('data-calculate'))calculateLab();
 if(b.hasAttribute('data-export'))download('tensegrity-progress-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(state,null,2),'application/json');
 if(b.hasAttribute('data-apply-import')&&pendingImport){state=pendingImport;pendingImport=null;save();render();announce('Your backup is restored on this device.');}
 if(b.hasAttribute('data-cancel-import')){pendingImport=null;$('#import-review').innerHTML='';}
 if(b.hasAttribute('data-retry'))location.reload();
});
document.addEventListener('input',e=>{
 if(e.target.id==='course-search'){let query=e.target.value.toLowerCase().trim(),list=routeLessons().filter(l=>(l.title+' '+l.concept+' '+l.objective).toLowerCase().includes(query));$('#phase-list').innerHTML=course.phases.map(p=>{let items=list.filter(l=>l.phase===p.id);return items.length?phaseHtml(p.id,items):'';}).join('')||'<div class="empty">No matching lessons. Try a broader topic.</div>';$('#search-count').textContent=list.length+' matching lessons';}
 if(e.target.id==='lesson-note'){let id=+e.target.dataset.lesson;state.notes[id]=e.target.value;$('#note-saved').textContent=save()?'Saved on this device.':'Not saved. Export a backup.';}
 if(e.target.closest('#lab-controls')){if(e.target.id==='solar-csv')return;const out=$('#'+e.target.id+'-value');if(out)out.textContent=e.target.value+' '+(e.target.dataset.unit||'');calculateLab();}
});
document.addEventListener('change',async e=>{
 if(e.target.id==='route'){state.route=e.target.value;save();render();}
 if(e.target.id==='font-size'){state.font=e.target.value;save();document.documentElement.style.setProperty('--scale',state.font==='large'?'1.18':'1');}
 if(e.target.id==='import-file'){try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Backup is too large');pendingImport=validateState(JSON.parse(await file.text()));$('#import-review').innerHTML='<div class="note">This backup contains '+Object.keys(pendingImport.completed).length+' reviewed lessons and '+Object.keys(pendingImport.notes).length+' notes. Restoring replaces this device’s current progress. Export your current record first if needed.</div><div class="actions"><button class="primary" data-apply-import type="button">Restore this backup</button><button class="secondary" data-cancel-import type="button">Cancel</button></div>';}catch(error){pendingImport=null;$('#import-review').textContent='Could not import: '+error.message;}}
});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);$('#main').focus({preventScroll:true});});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});
window.addEventListener('online',()=>getOfflineStatus());
try{const raw=localStorage.getItem(KEY);state=raw?validateState(JSON.parse(raw)):defaultState();}catch(e){state=defaultState();announce('Stored progress could not be read. A fresh session is open; import a valid backup if you have one.');}
(window.TensegrityCourse?Promise.resolve(window.TensegrityCourse):fetch('./data.json').then(r=>{if(!r.ok)throw Error('Course download failed');return r.json();})).then(data=>{if(data.lessons?.length!==48)throw Error('Course data is incomplete');course=data;render();registerTools();}).catch(e=>{$('#main').innerHTML='<section class="card"><h1>Could not open the course</h1><p>Connect to the internet for the first download, then try again.</p><button class="primary" data-retry type="button">Try again</button></section>';});
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{getOfflineStatus();navigator.serviceWorker.addEventListener('controllerchange',getOfflineStatus);}).catch(()=>{const b=$('#offline-status');if(b)b.textContent='Offline download unavailable in this browser';});
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const tools=[{name:'open_tensegrity_lesson',description:'Navigate to an existing course lesson. Does not mark it reviewed.',inputSchema:{type:'object',properties:{lessonId:{type:'integer',minimum:1,maximum:48}},required:['lessonId'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).length!==1||!Number.isInteger(input.lessonId)||!lesson(input.lessonId))throw Error('Invalid lesson ID');location.hash='lesson/'+input.lessonId;render();return {lessonId:input.lessonId,title:lesson(input.lessonId).title};}},{name:'read_tensegrity_progress',description:'Read counts of self-reported reviewed lessons and correct knowledge checks; does not expose private notes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('Expected empty input');return {reviewed:reviewed(),total:48,route:state.route,correctKnowledgeChecks:course.lessons.filter(l=>state.quiz[l.id]===l.mobileQuiz.correct).length};}}];tools.forEach(tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch(e){}});}
})();
