/* Offline teaching workflows. No simulated AI response or external record writes. */
(function(){'use strict';
const KEY='tensegrity.teach.v1',E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({schema:1,lang:'en',lesson:5,duration:60,quiet:false,large:false,observer:false,coach:0,observations:Array(8).fill(''),quiz:{},reviews:[]});
let state=fresh(),bridge=null,pending=null;
function validate(x){if(!x||x.schema!==1||!['en','zh'].includes(x.lang))throw Error('Unsupported assistant backup');const r=fresh();r.lang=x.lang;if(Number.isInteger(x.lesson)&&x.lesson>=1&&x.lesson<=48)r.lesson=x.lesson;if([30,45,60,90].includes(x.duration))r.duration=x.duration;for(const k of ['quiet','large','observer'])r[k]=x[k]===true;r.coach=Number.isInteger(x.coach)?Math.max(0,Math.min(7,x.coach)):0;if(Array.isArray(x.observations))r.observations=Array.from({length:8},(_,i)=>typeof x.observations[i]==='string'?x.observations[i].slice(0,2000):'');if(x.quiz&&typeof x.quiz==='object')for(const [k,v] of Object.entries(x.quiz))if(/^(basic-[0-4]|course-[1-9][0-9]?)$/.test(k)&&Number.isInteger(v)&&v>=0&&v<=2)r.quiz[k]=v;if(!Array.isArray(x.reviews)||x.reviews.length>100)throw Error('Invalid review list');r.reviews=x.reviews.map(v=>{if(!v||typeof v.evidence!=='string'||v.evidence.length>5000||!Array.isArray(v.ratings)||v.ratings.length!==4||v.ratings.some(n=>n!==null&&(!Number.isInteger(n)||n<0||n>3))||!['independent','verbal','visual','physical','unknown'].includes(v.support)||typeof v.id!=='string'||v.id.length>40||typeof v.date!=='string'||!Number.isFinite(Date.parse(v.date)))throw Error('Invalid learner review');return {id:v.id,evidence:v.evidence,date:v.date,ratings:v.ratings,support:v.support};});return r;}
try{const raw=localStorage.getItem(KEY);if(raw)state=validate(JSON.parse(raw));}catch(e){}
const T=(en,zh)=>state.lang==='zh'?zh:en;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){status(T('Not saved. Export your assistant backup before closing.','未能保存，请关闭前导出助手备份。'));return false;}}
function status(t){const n=document.querySelector('#assistant-status');if(n)n.textContent=t;}
const TOOLS={plan:['Lesson plan','课程计划'],coach:['Build coach','组装指导'],quiz:['Quiz','测验'],review:['Learner review','学习评估'],adapt:['Adapt a lesson','调整课程'],experiment:['Experiment plan','实验计划']};
const card=(title,body)=>'<section class="card"><h2>'+E(title)+'</h2>'+body+'</section>';
const p=t=>'<p>'+E(t)+'</p>',list=a=>'<ol>'+a.map(v=>'<li>'+E(v)+'</li>').join('')+'</ol>';
const button=(action,label,cls='secondary',extra='')=>'<button type="button" class="'+cls+'" data-teach="'+action+'" '+extra+'>'+E(label)+'</button>';
const field=(id,label,value='',type='text')=>'<label for="'+id+'">'+E(label)+'</label><input id="'+id+'" type="'+type+'" value="'+E(value)+'" maxlength="40">';
function current(){return bridge.course.lessons.find(l=>l.id===state.lesson);}
function selector(){return '<div class="teach-fields"><div><label for="teach-lesson">'+T('Course lesson','课程课题（原课题为英文）')+'</label><select id="teach-lesson">'+bridge.course.lessons.map(l=>'<option value="'+l.id+'"'+(l.id===state.lesson?' selected':'')+'>'+String(l.id).padStart(2,'0')+' · '+E(l.title)+'</option>').join('')+'</select></div><div><label for="teach-duration">'+T('Session length','课时长度')+'</label><select id="teach-duration">'+[30,45,60,90].map(n=>'<option value="'+n+'"'+(n===state.duration?' selected':'')+'>'+n+' '+T('minutes','分钟')+'</option>').join('')+'</select></div></div>';}
function access(){return '<div class="teach-options">'+[['quiet',T('Quiet setting with optional breaks','安静环境，可选择休息')],['large',T('Large task cards','大字任务卡')],['observer',T('Observe or draw instead of handling','可观察或画图，无需触摸')]].map(([k,v])=>'<label class="check-row"><input id="teach-'+k+'" type="checkbox"'+(state[k]?' checked':'')+'>'+E(v)+'</label>').join('')+'</div>';}
function adapted(){const a=[];if(state.quiet)a.push(T('Use a quiet work area; allow a pause whenever needed.','在安静区域学习，需要时可暂停。'));if(state.large)a.push(T('Use one action per large-print card with a visible completion cue.','大字任务卡每张只安排一个动作，明确完成标志。'));if(state.observer)a.push(T('Demonstrate understanding by observing, explaining or labelling a diagram. Handling is optional.','可通过观察、解释或标图展示理解，触摸操作为自选。'));return a;}
function plan(){const l=current(),total=state.duration,d=[5,Math.round(total*.2),Math.round(total*.3),Math.round(total*.2)];d.push(total-d.reduce((a,b)=>a+b,0));let at=0;const titles=[T('Predict','预测'),T('Explain and label','解释与标注'),T('Observe or try','观察或尝试'),T('Record and revise','记录与修正'),T('Exit ticket','离堂题')];const actions=[T('Predict the result before reading the worked example.','阅读示例前，先预测结果。'),l.concept,l.steps.join(' '),l.artifact,l.questions.join(' / ')];return card(T('Prepare your session','准备课程'),selector()+p(T('Default audience: adult beginners. Read the lesson materials and inspect the activity before teaching. Use diagram discussion if physical materials are unavailable.','默认对象：成人初学者。授课前阅读材料要求并检查活动；无实体材料时使用图示讨论。'))+p(l.materials))+card(T('Your timed plan','课时安排'),'<p class="chip">'+total+' '+T('minutes','分钟')+'</p><h3>'+E(l.title)+'</h3>'+p(l.objective)+'<div class="table-wrap"><table><thead><tr><th>'+T('Time','时间')+'</th><th>'+T('Activity','活动')+'</th><th>'+T('Learner task','学习任务')+'</th></tr></thead><tbody>'+d.map((n,i)=>{const start=at;at+=n;return '<tr><td>'+start+'–'+at+'</td><td>'+titles[i]+'</td><td>'+E(actions[i])+'</td></tr>';}).join('')+'</tbody></table></div>'+p(T('Course explanations and source questions remain in English. Chinese controls and teaching guidance do not translate the whole course.','原课程解释与题目保留英文；中文界面与教学指导并不代表整套课程已翻译。'))+'<details><summary>'+T('Instructor answer key','教师答案')+'</summary>'+list(l.answers)+'</details>'+list(adapted())+'<div class="actions">'+button('download-plan',T('Download plan','下载计划'))+'<a class="secondary" href="#lesson/'+l.id+'">'+T('Open lesson','打开课程')+'</a></div>');}
const BUILD=[
['Label and verify','标注与核对','Label nodes 0,1,2 (bottom) and 3,4,5 (top). Verify the three struts and nine cables against the endpoint schedule. Test a gentle sample joint and mark its position.','下层节点标为0、1、2，上层为3、4、5。根据端点表核对3根压杆与9条拉索。轻轻测试一个连接点，标记其位置。'],
['Support the geometry','支撑几何位置','Keep all six node positions supported by a jig. Place struts 0–4, 1–5 and 2–3. Do not connect rods along their lengths.','用定位支架支撑六个节点。压杆连接0–4、1–5、2–3；杆身之间不互相连接。'],
['Bottom ring','下层环索','Loosely attach cables 0–1, 1–2 and 2–0. Check labels before adjusting.','松松连接拉索0–1、1–2、2–0。调整前检查标签。'],
['Top ring','上层环索','Loosely attach cables 3–4, 4–5 and 5–3. Confirm node order and the source +30° top twist convention.','松松连接拉索3–4、4–5、5–3。核对节点顺序与原说明上层+30°扭转约定。'],
['Cross cables','交叉拉索','Attach 0–3, 1–4 and 2–5 with adjustable connections. Keep the jig supporting the model.','以可调整的连接方式连接0–3、1–4、2–5，保持定位支架支撑。'],
['Gently snug','轻柔收紧','Adjust in small alternating increments. Watch witness marks, rod contact and fraying. Keep your face away from stretched parts. Stop on sudden slip or damage.','交替小幅调整，检查位移标记、杆件接触与磨损；面部远离绷紧部件。突然滑脱或损坏时立即停止。'],
['Reduce support','逐渐减少支撑','Only gradually reduce jig support when joints stay controlled. If it collapses, resupport and inspect the labels and joints. Do not add loads.','仅在连接保持可控时逐渐减少支架支撑。坍塌时重新支撑并检查标签与连接，勿加额外载荷。'],
['Record deviations','记录差异','Record measured spans, node height, joint details and differences from the ideal geometry. A standing model is not a load rating.','记录实际跨度、节点高度、连接细节及与理想几何的差异。模型能站立不代表已获得承载等级。']];
function coach(){const b=BUILD[state.coach];return card(T('Three-strut tabletop pilot','三压杆桌面试作'),p(T('The source geometry is numerically checked; the physical workshop procedure remains a pilot. Use blunt lightweight rods, adjustable low-tension cords, labels, ruler and a support jig.','原几何已作数值检查，实体教学流程仍属试作。使用轻质钝头杆、低张力可调拉索、标签、尺与定位支撑。'))+p(T('Ideal spans: ring 138.564 mm; cross cable 145.996 mm; strut 208.531 mm. These are node spans, NOT universal cut lengths. Match actual joint offsets and rod geometry before assembly.','理想节点跨度：环索138.564毫米，交叉索145.996毫米，压杆208.531毫米。它们不是通用裁切长度；组装前匹配真实连接偏移与杆件尺寸。'))+'<a href="./resources/three-strut-prism.md">'+T('Full source build guide','完整组装说明（英文）')+'</a>')+card(T('Step ','步骤 ')+(state.coach+1)+' / 8 · '+T(b[0],b[1]),'<progress max="8" value="'+(state.coach+1)+'" aria-label="'+T('Current coaching step','当前指导步骤')+'"></progress>'+p(T(b[2],b[3]))+'<label for="teach-observation">'+T('What did you observe?','你观察到什么？')+'</label><textarea id="teach-observation" maxlength="2000" placeholder="'+T('Labels, joint marks, slack, differences…','标签、连接标记、松弛、差异……')+'">'+E(state.observations[state.coach])+'</textarea><div class="actions">'+button('coach-back',T('Previous','上一步'),'secondary',state.coach===0?'disabled':'')+button('coach-next',T(state.coach===7?'Finish and review':'Save observation & continue',state.coach===7?'完成并回顾':'保存观察并继续'),'primary')+'</div><p class="small muted">'+T('Step position is saved locally. It does not certify a successful build.','步骤进度保存在本机，并不证明组装成功。')+'</p>')+card(T('If the model drifts or collapses','模型漂移或坍塌时'),list([T('Support the model and reduce tension gently.','支撑模型，轻柔减小张力。'),T('Compare labelled endpoints with the schedule.','对照端点表检查标记。'),T('Inspect joint marks and actual twist; adjust one cause at a time.','检查连接标记和实际扭转，每次只处理一个原因。')]))+(state.coach===7?card(T('Your observations','你的观察记录'),BUILD.map((x,i)=>'<h3>'+T(x[0],x[1])+'</h3>'+p(state.observations[i]||T('Not observed','未观察'))).join('')):'');}
const BASIC=[
[['Which force can a flexible cable carry?','柔性拉索能承受什么力？'],[['Tension','拉力'],['Compression','压力'],['Either equally','两者一样']],0,['An ideal cable pulls; it cannot push like a rod.','理想拉索传递拉力，不能像杆件那样传递推力。']],
[['What is the intended primary role of a strut?','压杆主要承受什么？'],[['Compression','压力'],['Electrical current','电流'],['No force','不承受力']],0,['A strut carries compression and may buckle.','压杆承受压力，也可能发生屈曲。']],
[['A cable is slack. What can you conclude?','拉索松弛时，你能得出什么结论？'],[['It is stronger','它更强了'],['It is not taut','它未绷紧'],['Every member failed','所有构件都坏了']],1,['Slack alone does not determine the whole structure’s stability.','仅凭松弛不能判断整个结构的稳定性。']],
[['Does a floating appearance prove tensegrity?','悬浮外观能证明张拉整体吗？'],[['Always','总能'],['Only if it is large','只有大结构能'],['No; inspect connectivity','不能，需检查连接关系']],2,['Inspect the tension network and separated compression members.','需检查受拉网络及彼此分离的受压构件。']],
[['Are ideal node spans universal cutting lengths?','理想节点跨度是通用裁切长度吗？'],[['Yes','是'],['No; joints and stretch matter','不是，连接与伸长会影响'],['Only for every cable','仅对所有拉索是']],1,['Joint offsets, knot allowances and stretch affect physical lengths.','连接偏移、打结余量与伸长会影响实体长度。']]];
function quiz(){const l=current(),q=l.mobileQuiz;let all=BASIC.map((v,i)=>({key:'basic-'+i,question:T(...v[0]),options:v[1].map(x=>T(...x)),correct:v[2],why:T(...v[3])}));all.push({key:'course-'+l.id,question:q.question,options:q.options,correct:q.correct,why:q.explanation});const answered=all.filter(x=>state.quiz[x.key]!==undefined),correct=answered.filter(x=>state.quiz[x.key]===x.correct).length;return card(T('Practice, then explain','先练习，再解释'),selector()+p(T('Five bilingual foundation checks plus one authored course check in English. Answers appear only after you choose. Quiz results do not certify practical skill.','五道双语基础题，另加一道原课程英文题。选择后才显示答案；测验结果不证明实际操作能力。'))+p(correct+' / '+answered.length+' '+T('answered correctly; ','已答题正确；')+answered.length+' / 6 '+T('attempted','已作答')))+all.map((x,i)=>card((i+1)+'. '+x.question,x.options.map((v,j)=>'<button type="button" class="quiz-option" data-teach="answer" data-key="'+x.key+'" data-choice="'+j+'" aria-pressed="'+(state.quiz[x.key]===j)+'">'+E(v)+'</button>').join('')+(state.quiz[x.key]===undefined?'':'<div class="feedback'+(state.quiz[x.key]===x.correct?'':' wrong')+'">'+E(T(state.quiz[x.key]===x.correct?'Correct. ':'Review this idea. ',state.quiz[x.key]===x.correct?'正确。':'请复习此概念。')+x.why)+'</div>'))).join('')+button('reset-quiz',T('Clear these practice answers','清除本组答案'));}
function summary(r){const seen=r.ratings.filter(x=>x!==null);return {count:seen.length,average:seen.length?seen.reduce((a,b)=>a+b,0)/seen.length:null};}
const dims=()=>[T('Force roles','构件受力'),T('Connectivity / assembly','连接与组装'),T('Observation / measurement','观察与测量'),T('Explanation / reflection','解释与反思')];
function review(){return card(T('Record observed evidence','记录已观察证据'),p(T('Use an anonymous label. Keep diagnoses and personal information out of notes. Ratings are entered by the facilitator; no automatic judgment is made from the text.','使用匿名编号，勿填写诊断或个人信息。评分由教学者输入，助手不会自动根据文字作判断。'))+'<form id="teach-review-form">'+field('teach-learner',T('Anonymous learner label','匿名学习者编号'),'L01')+'<label for="teach-evidence">'+T('Observed evidence','已观察到的证据')+'</label><textarea id="teach-evidence" maxlength="5000" required></textarea><div class="teach-fields">'+dims().map((v,i)=>'<div><label for="teach-rating-'+i+'">'+v+'</label><select id="teach-rating-'+i+'">'+[[null,T('Not observed','未观察')],[0,T('0 · Not yet demonstrated','0 · 尚未展示')],[1,T('1 · Partial','1 · 部分')],[2,T('2 · Adequate evidence','2 · 足够证据')],[3,T('3 · Evidence plus reasoning','3 · 证据与推理')]].map(([k,t])=>'<option value="'+(k===null?'':k)+'">'+t+'</option>').join('')+'</select></div>').join('')+'</div><label for="teach-support">'+T('Support used (separate from understanding)','所用支持（与理解分开记录）')+'</label><select id="teach-support">'+[['unknown',T('Not recorded','未记录')],['independent',T('Independent','独立')],['verbal',T('Verbal prompt','口头提示')],['visual',T('Visual prompt','视觉提示')],['physical',T('Physical assistance','动作协助')]].map(([k,v])=>'<option value="'+k+'">'+v+'</option>').join('')+'</select><button class="primary" type="submit">'+T('Save review on this device','在本机保存评估')+'</button></form>')+card(T('Saved reviews','已保存评估'),state.reviews.length?state.reviews.slice().reverse().map(r=>{const s=summary(r);return '<article class="teach-review"><h3>'+E(r.id)+' · '+E(new Date(r.date).toLocaleDateString())+'</h3>'+p(r.evidence)+p(T('Coverage: ','观察覆盖：')+s.count+'/4 · '+T('Average: ','平均：')+(s.average===null?T('Not available','无'):s.average.toFixed(2)))+list(dims().map((d,i)=>d+': '+(r.ratings[i]===null?T('Not observed','未观察'):r.ratings[i])))+p(T('Support: ','支持：')+r.support)+p(T('Next: collect evidence for an unobserved dimension; preserve the learner’s chosen supports.','下一步：收集尚未观察维度的证据，保留学习者选择的支持。'))+'</article>';}).join(''):p(T('No reviews yet. Missing evidence is excluded from averages, not scored zero.','尚无评估。缺失证据不计入平均分，也不记零分。')));}
function adapt(){return card(T('Keep the objective. Choose the support.','保留目标，选择支持。'),selector()+p(current().objective)+access()+list(adapted().length?adapted():[T('Use the standard task sequence, with learner choice of response format.','使用标准任务顺序，学习者可选择回答方式。')])+p(T('These are teaching adjustments, not a treatment. Ask the learner what helps; do not infer a diagnosis.','这些是教学调整而非治疗。询问学习者哪些安排有帮助，勿推断诊断。')))+card(T('One action per card','每张卡一个动作'),'<div class="teach-cards '+(state.large?'large':'')+'">'+[T('Predict what happens. Finish with one sentence or drawing.','预测结果。完成一句话或一幅图即可。'),T('Observe the demonstration or diagram. Point to one relevant member.','观察示范或图示，指出一个相关构件。'),T('Record one observation with units if measured.','记录一个观察；若有测量则写明单位。'),T('Explain one difference from your prediction.','解释与预测不同的一点。')].map((v,i)=>'<div><span class="chip">'+(i+1)+'</span>'+p(v)+'</div>').join('')+'</div>');}
function experiment(){return card(T('A controlled comparison','受控比较实验'),selector()+p(T('Compare joint drift over ten minutes with no added load. Prepare a supported lightweight pilot or use existing measurements if handling is unavailable.','在无额外载荷下比较十分钟内的连接漂移；准备有支撑的轻质试作，无法操作时使用已有测量。'))+list([T('Question: do witness marks move between the start and ten minutes?','问题：位移标记是否在开始与十分钟后改变？'),T('Baseline: record initial node height and joint mark position (mm).','基线：记录初始节点高度及连接标记位置（毫米）。'),T('Change one factor: choose one attachment method; compare with a control method.','只改变一个因素：选择一种连接方法，与对照方法比较。'),T('Hold geometry, materials, measurement method, elapsed time and support conditions constant.','保持几何、材料、测量方法、经过时间与支撑条件一致。'),T('Repeat three controlled trials if feasible. Record actual readings; do not fabricate absent data.','可行时重复三次受控试验，记录真实读数，不编造缺失数据。'),T('Stop on sudden slip, fraying or damage. A small trial does not establish load capacity.','突然滑脱、磨损或损坏时停止。小型试验不能证明承载能力。')]))+card(T('Your test brief','你的实验简报'),'<label for="teach-experiment-note">'+T('Variable, baseline, units, repeats and limitations','变量、基线、单位、重复次数与局限')+'</label><textarea id="teach-experiment-note" maxlength="4000"></textarea>'+button('download-experiment',T('Download experiment brief','下载实验简报'))+'<a class="download-link" href="./resources/experiment.md">'+T('Open source worksheet','打开原实验表')+'</a>');}
function promptText(){const l=current(),tool=(location.hash.slice(1).split('/')[1]||'plan');return 'Use Tensegrity Teaching Assistant if available. Otherwise follow these teaching principles: distinguish tension from compression; keep physical work to lightweight controlled tabletop models; ideal spans are not universal cut lengths; do not infer strength or mastery without evidence; track support separately; mark missing observations as not observed.\nTask: '+(TOOLS[tool]?.[0]||'Lesson plan')+'\nLanguage: '+(state.lang==='zh'?'Chinese':'English')+'\nSession: '+state.duration+' minutes\nCourse lesson '+l.id+': '+l.title+'\nObjective: '+l.objective+'\nConcept: '+l.concept+'\nMaterials: '+l.materials+'\nActivity: '+l.steps.join('; ')+'\nAdaptations: '+adapted().join('; ')+'\nMy recorded build observations: '+state.observations.filter(Boolean).join('; ')+'\nPrepare useful guidance and state assumptions. Ask for observations before drawing conclusions.';}
function handoff(){return card(T('Continue with your AI assistant','继续使用AI助手'),p(T('The tools above run offline from course content. For a custom conversation, copy your lesson context and paste it into ChatGPT. ChatGPT needs internet and its own account; no AI API is connected inside this app.','以上工具根据课程内容离线运行。自定义对话时，复制课程背景并粘贴到ChatGPT。ChatGPT需要联网及其账户；本应用尚未连接AI API。'))+'<div class="actions">'+button('copy-context',T('Copy lesson context','复制课程背景'),'primary')+'<a class="secondary" href="https://chatgpt.com/" target="_blank" rel="noopener">'+T('Open ChatGPT','打开ChatGPT')+'</a></div><details><summary>'+T('View text to copy','查看待复制文字')+'</summary><textarea id="teach-context" readonly>'+E(promptText())+'</textarea></details>');}
function render(ctx,arg){bridge=ctx;let [tool,lesson]=String(arg||'plan').split('/');if(!TOOLS[tool])tool='plan';if(Number.isInteger(+lesson)&&+lesson>=1&&+lesson<=48){state.lesson=+lesson;save();}return '<div id="teaching-assistant"><div class="teach-heading"><div><p class="eyebrow">'+T('Teaching assistant','教学助手')+'</p><h1 class="page-title">'+T('Turn a lesson into an activity.','把课程变成实践。')+'</h1></div><div><label for="teach-language">'+T('Assistant language','助手语言')+'</label><select id="teach-language"><option value="en"'+(state.lang==='en'?' selected':'')+'>English</option><option value="zh"'+(state.lang==='zh'?' selected':'')+'>中文</option></select></div></div><p class="muted">'+T('Guided tools · Works offline · Saves on this device','引导工具 · 可离线使用 · 保存在本机')+'</p><div class="lab-tabs" aria-label="'+T('Teaching tools','教学工具')+'">'+Object.entries(TOOLS).map(([k,v])=>'<a class="lab-tab" href="#assistant/'+k+'"'+(k===tool?' aria-current="page"':'')+'>'+T(...v)+'</a>').join('')+'</div><p id="assistant-status" role="status" aria-live="polite"></p>'+({plan,coach,quiz,review,adapt,experiment}[tool]())+handoff()+card(T('Assistant backup','助手备份'),p(T('Build observations, quiz choices and learner reviews stay on this device. Export them separately from your course-progress backup.','组装观察、测验选择与评估保存在本机；它们需独立于课程进度备份导出。'))+'<div class="actions">'+button('export',T('Export assistant backup','导出助手备份'))+'<label class="secondary">'+T('Import assistant backup','导入助手备份')+'<input type="file" id="teach-import" accept=".json,application/json" hidden></label></div><div id="teach-import-review"></div>')+'</div>';}
function refresh(){if(bridge)bridge.refresh();}
function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:name.endsWith('.json')?'application/json':'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function textPlan(){const l=current(),total=state.duration,d=[5,Math.round(total*.2),Math.round(total*.3),Math.round(total*.2)];d.push(total-d.reduce((a,b)=>a+b,0));let at=0;const names=[T('Predict','预测'),T('Explain and label','解释与标注'),T('Observe or try','观察或尝试'),T('Record and revise','记录与修正'),T('Exit ticket','离堂题')];const timing=d.map((n,i)=>{const a=at;at+=n;return a+'–'+at+' '+names[i];}).join('\n');return l.title+'\n'+l.objective+'\n'+state.duration+' minutes\n'+timing+'\nMaterials: '+l.materials+'\nSteps:\n'+l.steps.map((v,i)=>(i+1)+'. '+v).join('\n')+'\nQuestions:\n'+l.questions.join('\n')+'\nInstructor answers:\n'+l.answers.join('\n')+'\nAdaptations:\n'+adapted().join('\n');}
document.addEventListener('click',async ev=>{const b=ev.target.closest('[data-teach]');if(!b||!bridge)return;const action=b.dataset.teach;
if(action==='coach-back'){state.coach=Math.max(0,state.coach-1);save();refresh();}
if(action==='coach-next'){const n=document.querySelector('#teach-observation');state.observations[state.coach]=n?.value||'';if(state.coach<7){state.coach++;save();refresh();}else{save();refresh();status(T('Observations saved. Review the notes below; no successful-build rating is implied.','观察已保存，请回顾下方笔记；这不代表成功组装评级。'));}}
if(action==='answer'){state.quiz[b.dataset.key]=+b.dataset.choice;save();refresh();}
if(action==='reset-quiz'){for(const k of [...BASIC.map((_,i)=>'basic-'+i),'course-'+state.lesson])delete state.quiz[k];save();refresh();}
if(action==='export')download('tensegrity-assistant-backup.json',JSON.stringify(state,null,2));
if(action==='restore'&&pending){state=pending;pending=null;save();refresh();status(T('Assistant backup restored. Course progress was not changed.','助手备份已恢复，课程进度未改变。'));}
if(action==='cancel-import'){pending=null;document.querySelector('#teach-import-review').textContent='';}
if(action==='download-plan')download('tensegrity-lesson-plan.txt',textPlan());
if(action==='download-experiment')download('tensegrity-experiment.txt',document.querySelector('#teach-experiment-note').value+'\n\n'+document.querySelector('#teaching-assistant').innerText.split(T('Continue with your AI assistant','继续使用AI助手'))[0]);
if(action==='copy-context'){try{await navigator.clipboard.writeText(promptText());status(T('Copied. Open ChatGPT and paste the lesson context.','已复制，请打开ChatGPT并粘贴课程背景。'));}catch(e){const n=document.querySelector('#teach-context');n.closest('details').open=true;n.focus();n.select();status(T('Select and copy the text below, then paste it into ChatGPT.','请复制下方选中文字，然后粘贴至ChatGPT。'));}}
});
document.addEventListener('input',e=>{if(e.target.id==='teach-observation'){state.observations[state.coach]=e.target.value;save();}});
document.addEventListener('change',async e=>{const id=e.target.id;if(id==='teach-language'){state.lang=e.target.value;save();refresh();}if(id==='teach-lesson'){state.lesson=+e.target.value;save();const parts=location.hash.split('/');if(parts.length>2)location.hash='assistant/'+(parts[1]||'plan');else refresh();}if(id==='teach-duration'){state.duration=+e.target.value;save();refresh();}for(const k of ['quiet','large','observer'])if(id==='teach-'+k){state[k]=e.target.checked;save();refresh();}
if(id==='teach-import'){try{const f=e.target.files[0];if(!f)return;if(f.size>2000000)throw Error('File too large');pending=validate(JSON.parse(await f.text()));document.querySelector('#teach-import-review').innerHTML=p(T('Restore replaces assistant records on this device. Export your current backup first.','恢复会替换本机助手记录，请先导出现有备份。'))+button('restore',T('Restore backup','恢复备份'),'primary')+button('cancel-import',T('Cancel','取消'));}catch(err){pending=null;status(T('Invalid assistant backup: ','助手备份无效：')+err.message);}}
});
document.addEventListener('submit',e=>{if(e.target.id!=='teach-review-form')return;e.preventDefault();if(state.reviews.length>=100){status(T('Review limit reached. Export a backup.','已达评估上限，请导出备份。'));return;}const evidence=document.querySelector('#teach-evidence').value.trim(),id=document.querySelector('#teach-learner').value.trim();if(!id||!evidence){status(T('Enter a learner label and observed evidence.','请填写学习者编号与已观察证据。'));return;}state.reviews.push({id,evidence,date:new Date().toISOString(),ratings:[0,1,2,3].map(i=>{const v=document.querySelector('#teach-rating-'+i).value;return v===''?null:+v;}),support:document.querySelector('#teach-support').value});save();refresh();status(T('Review saved on this device.','评估已保存在本机。'));});
window.TensegrityTeaching={render,validate,summary};
})();
