"""Authored lesson content. Used to rebuild Markdown, assessments and the reader."""
PHASES = [
('orientation','Orientation and workshop setup',6),
('structural-intuition','Structural intuition',12),
('geometry-and-making','Geometry and making',18),
('statics','Statics and useful mathematics',18),
('materials-and-failure','Materials and failure',16),
('digital-models','Form-finding and digital models',20),
('dynamics','Dynamics and resilience',16),
('solar-applications','Solar and Singapore applications',18),
('sensors-and-ai','Sensors, controls and AI',16),
('accessible-teaching','Accessible teaching and workforce skills',12),
('community-delivery','Community design and delivery',12),
('capstone','Capstone and research judgment',16),
]
LESSONS=[]
def L(title,objective,concept,worked,materials,steps,expected,pitfall,questions,answers,artifact,lab=None):
    LESSONS.append(dict(title=title,objective=objective,concept=concept,worked=worked,materials=materials,
                        steps=steps,expected=expected,pitfall=pitfall,questions=questions,answers=answers,artifact=artifact,lab=lab))

L('Goals and placement',
  'Choose a learning route and identify what you can already demonstrate.',
  'A goal names an observable result. “Understand tensegrity” is broad; “assemble a labeled prism and explain its load paths” can be checked. Prior experience matters only when it transfers to this task. Mathematics, making and teaching are separate skills, so placement should not be based on one total score.',
  'A learner can assemble a kit but cannot distinguish mass in kg from force in N. They may use making experience while still completing lessons 13–16. For Ivan, the default route ends in a tabletop solar sculpture and reproducible workshop.',
  'Paper, pencil, optional phone camera; no tools or software required.',
  ['Write one intended beneficiary and one finished artifact.','Without searching, explain tension and compression; sketch a structure; convert 100 mm to m; explain a fair comparison.','Mark each task as independent, assisted or unfamiliar.','Choose the solar-builder route in learning-paths/routes.json, or another listed route.','Write the next two sessions and the evidence you will produce.'],
  'The record reveals different strengths rather than labeling the learner as simply beginner or advanced.',
  'Do not skip prerequisites because you recognize vocabulary. Demonstrate the task or keep the lesson.',
  ['What makes a goal assessable?','Does strong craft ability imply statics competence?','What is this course’s first milestone?'],
  ['A named action and observable artifact.','No; assess each skill separately.','A labeled, repeatable three-strut model and explanation.'],
  'A one-page personal brief with route, placement evidence and two session dates.')

L('Materials and tools',
  'Prepare a small kit and distinguish geometric dimensions from connection allowances.',
  'A model includes members and joints. An ideal node is a point; a real knot, loop or cap occupies space and may slip. Record both the distance between node centers and the total cut length. Start with blunt, lightweight struts, cord and adjustable loops; use elastic only as a clearly documented classroom substitution.',
  'A target cable has a 140 mm node-to-node span. Two 15 mm knot allowances suggest an initial 170 mm cut, but actual knot take-up must be checked on a sample. Never treat 170 mm as the structural member length.',
  'Blunt craft struts or a classroom kit, cord, ruler, reusable clips, tape, tray and optional pre-cut loops. Cutting is performed by a competent adult when needed.',
  ['Inventory each item and state its role.','Inspect strut ends and remove sharp or damaged parts.','Make one low-tension sample joint; mark its start position.','Measure its node span, overall length and repeatability.','Write a bill of materials using templates/bill-of-materials.csv.'],
  'The materials list includes joint details, not only rods and strings.',
  'Avoid thin wire, strong elastic, large suspended loads and improvised powered tools in introductory work.',
  ['Why is cut length different from node span?','What should an inspection reject?','Why record elastic-band use?'],
  ['Knots and attachments consume additional length.','Sharp ends, damage or insecure joints.','Its nonlinear stretch and creep differ from ideal cable assumptions.'],
  'A materials list and a photographed, measured sample joint.')

L('Observation and measurement',
  'Measure repeatedly and state resolution without inventing precision.',
  'Resolution is the smallest readable increment. Repeatability describes how readings vary when the measurement is repeated. Neither guarantees accuracy: a misaligned ruler can produce repeatable but biased readings. Label the endpoints, units and measuring method so somebody else can reproduce your result.',
  'Three readings are 139, 140 and 139 mm. Their mean is 139.33 mm, but a 1 mm ruler does not justify reporting the span as exactly 139.333333 mm. Report the raw readings and approximately 139 mm with the instrument resolution.',
  'Ruler with known markings, cord sample, paper and stable flat surface.',
  ['Define the two measurement endpoints with tape marks.','Read the span without pulling the cord harder each time.','Remove and replace the ruler for three readings.','Calculate mean and range: maximum minus minimum.','Exchange instructions with another person or remeasure after a break; compare.'],
  'Small variation is visible in the raw record. Differences prompt a method check before a design change.',
  'Looking diagonally causes parallax. Changing tension changes the specimen rather than just the reading.',
  ['Is repeatability the same as accuracy?','What is the range of 139,140,139 mm?','Why keep raw readings?'],
  ['No; repeated measurements can share a bias.','1 mm.','They reveal variation and allow checking the summary.'],
  'Three readings, endpoint sketch, mean, range and instrument resolution.')

L('Lab notebook and safe handling',
  'Make a traceable experiment record and define a stop condition.',
  'A notebook separates prediction from observation. Record the setup before testing, then the result, then your interpretation. A revised design receives a new version identifier; do not overwrite the first result. Stop conditions are observable events such as joint slip or a damaged strut, not vague requests to “be careful.”',
  'Prediction: shortening C0 will tilt the prism. Observation: C0 was shortened approximately 2 mm and the top moved sideways, but the angle was not measured. Interpretation: the result suggests asymmetry; it does not establish a quantitative tilt law.',
  'Notebook template, pencil, tray and a low-tension sample joint.',
  ['Copy templates/experiment.md into a private local folder.','Assign a specimen ID and write your prediction.','Record dimensions, boundary conditions, tools and one stop condition.','Gently repeat the sample-joint handling test from lesson 02.','Log what occurred, including missing measurements; choose one next action.'],
  'A reader can distinguish the expected result, observed fact and explanation.',
  'Keep faces away from stretched components. Stop on slip, fraying or unexpected motion. Do not add learner-identifying photographs to a public repository.',
  ['When is the prediction written?','What distinguishes observation from inference?','Name a stop condition.'],
  ['Before testing.','Observation reports measured or seen events; inference explains them.','Visible joint slip, damage or unexpected release.'],
  'A completed experiment record with a version ID and stop condition.')

L('Tension versus compression',
  'Identify what a flexible cable and a strut can carry.',
  'Tension pulls along a member; compression pushes along it. A flexible cord cannot reliably resist compression: it becomes slack or bends. A strut can carry compression but may buckle. In our numerical convention positive force means tension and negative force means compression; the sign must be stated rather than assumed.',
  'A 2 N tensile cable pulls each attached node toward the other. The two end forces are equal and opposite. A compressed strut pushes its nodes away from each other. The net force on the whole unloaded member can be zero while internal force is nonzero.',
  'String, soft sponge, blunt craft stick, pencil and paper.',
  ['Gently pull the string and draw forces at its two ends.','Move the ends together and observe slack.','Gently compress a sponge to represent compression.','Draw end forces on a strut without bending it to failure.','Label three components in a reference prism as tension or compression members.'],
  'The learner sees that a balance of external forces does not mean the member is unstressed.',
  'Do not confuse force sign with spatial direction. Negative compression is a convention, not a downward force.',
  ['Can a flexible cable push?','Does zero net force imply zero internal force?','What risk limits a slender compressed strut?'],
  ['No in this idealization; it slackens.','No; opposite end forces can balance.','Buckling, alongside material and connection limits.'],
  'Two force sketches and an annotated prism image.')

L('Load paths',
  'Trace a load through connections to external supports.',
  'A load path follows how forces transfer between members and eventually to supports. Internal forces occur in action–reaction pairs; reactions from the table or anchors are external to the structure. A complete diagram must say which object is being isolated. A free prism with only self-stress is a different problem from a prism resting on a table under gravity.',
  'For a tabletop model with total mass 0.2 kg, its weight is approximately 1.962 N using g=9.81 m/s². In static vertical balance the sum of upward table reactions is 1.962 N. Equal individual reactions require additional symmetry assumptions.',
  'A model or the supplied prism drawing; paper and colored pencils.',
  ['Draw a boundary around the entire model.','Mark gravity and table contact forces outside that boundary.','Choose one top node and draw its connected members.','Trace the possible force routes to bottom contacts.','Explain why the free self-stress model has no table reactions but the physical model does.'],
  'The whole-structure diagram includes external forces while the node diagram contains member forces.',
  'Do not distribute weight equally without checking symmetry, contact and center of mass.',
  ['Where does a tabletop load ultimately go?','Are table reactions internal?','What is the weight of 0.2 kg?'],
  ['Into the table and its supports.','No; they are external to the isolated model.','About 1.962 N.'],
  'Whole-model and single-node load-path sketches.')

L('Prestress and slack',
  'Explain internal force before external loading and detect slack.',
  'Prestress is an initial internal force state. In a free ideal tensegrity, self-stress can balance at every node without external loading. Cables must remain tensile in the intended state. Prestress may alter stiffness, but increasing it also raises joint demand and strut compression. Equilibrium, stability and material capacity are different checks.',
  'For a unilateral spring with stiffness 100 N/m, rest length 0.14 m and current length 0.15 m, tension is 1 N. At 0.13 m the model returns 0 N, not −1 N, because a cable does not carry compression.',
  'Cord or low-tension elastic sample, ruler; optional Python 3.10 or newer.',
  ['Observe a cord at three gentle extensions without releasing it suddenly.','Record when it is slack and when it is taut.','Calculate the two example spring forces.','If using Python, run the spring lab at lengths 0.15 and 0.13 m.','Explain why a spring estimate is not proof of prism stability.'],
  'The calculation clips compressive cable force to zero; physical response depends on the actual material.',
  'Do not infer cable force from appearance alone. Stronger tightening can cause joint failure or buckling.',
  ['What is self-stress?','What force is predicted below rest length?','Does extra prestress always help?'],
  ['An internal member-force state balancing without external loads.','Zero in the tension-only spring model.','No; it also increases forces and may change failure risk.'],
  'A slack/taut observation table and two checked calculations.', 'spring')

L('Tensegrity and structural lookalikes',
  'Classify structures by connectivity and member roles rather than appearance.',
  'The classic tensegrity picture uses separated compression members coupled by a continuous tension network. Mathematical tensegrity frameworks also include broader cable/strut/bar definitions. A floating-platform display can be an excellent statics example while differing from the classic isolated-strut arrangement. State the definition you are using.',
  'A platform hung from a central cable and stabilized by side ties is not automatically the same topology as a three-strut prism. Both may contain tension and compression, but their supports and connected compression paths differ.',
  'Supplied prism drawing, a sketch of a suspended platform, pencil.',
  ['Mark every node and member in both structures.','Label cables, struts and any rigid connected frames.','Trace the compression connectivity and external supports.','Write a classification with the definition stated first.','Explain both designs without describing either as magic or antigravity.'],
  'The comparison remains accurate even when marketing names are inconsistent.',
  'A structure does not float without load transfer. Do not treat terminology debates as substitutes for force diagrams.',
  ['What should classification state first?','Does “floating” mean no load path?','Can a lookalike still teach statics?'],
  ['The definition being applied.','No; forces reach supports.','Yes, with an accurate explanation of topology.'],
  'A comparison table of nodes, members, supports and definitions.')

L('Nodes and connectivity',
  'Translate the prism into a node and member schedule.',
  'Topology says which nodes are connected; geometry says where they are. Our prism uses bottom nodes 0,1,2 and top nodes 3,4,5. B and T are triangle-edge cables; C joins corresponding bottom/top nodes; S joins bottom i to top (i+1) modulo 3. The six nodes and twelve members must be labeled consistently across drawings and code.',
  'C0 connects 0–3. S0 connects 0–4, S1 connects 1–5 and S2 connects 2–3. At node 0, B0, B2, C0 and S0 meet. A missing C0 changes topology even if the model still looks similar.',
  'Printed assets/prism.svg, member table in builds/three-strut-prism.md, label stickers.',
  ['Label all six nodes on a drawing.','Copy all twelve member endpoint pairs.','List the four members meeting node 0.','Count how many times each member endpoint appears across nodes.','Match the drawing labels to the supplied digital prism output.'],
  'There are nine cables and three struts; each node has degree four.',
  'Mixing top-node order changes the geometry and may create intersecting or unbalanced members.',
  ['How many cables are in this topology?','What does S2 connect?','What is the difference between topology and geometry?'],
  ['Nine.','Node 2 to node 3.','Connectivity versus coordinates.'],
  'A complete labeled node/member schedule.')

L('Build a three-strut prism',
  'Assemble a low-tension classroom model using a defined topology.',
  'A jig supports nodes while cables are connected. Begin with adjustable loops and small prestress rather than forcing fixed cut lengths. The target ideal geometry has radius 80 mm, height 140 mm and a 30° top-triangle rotation. Joints and material compliance mean the physical model will differ from the point-node calculation.',
  'Ideal member spans are about 138.56 mm for triangle edges, 146.00 mm for cross cables and 208.53 mm for struts. Use the generated member table for exact values. Knot allowances and the node-center definition are additional; the values are not universal cut lengths.',
  'Three blunt lightweight struts, nine adjustable cord segments, soft secure attachment loops, tray, optional cardboard positioning jig; see the build guide.',
  ['Read builds/three-strut-prism.md completely and inspect your joint samples.','Mark bottom node positions and rotated top positions on the jig.','Place struts along 0–4, 1–5 and 2–3 while the jig supports them.','Attach bottom and top triangle cables, then C0,C1,C2; snug gradually in small symmetric increments.','Remove support only if joints hold; record all node spans and photograph the model.'],
  'A connected tabletop model should hold a recognizable prism shape if joints and prestress are suitable; physical success is not guaranteed by the ideal calculation.',
  'If it collapses, return it to the jig and check node order, loose joints and unequal spans. Do not cure collapse by adding high tension.',
  ['Why use adjustable loops first?','Which strut connects node 0?','Does this repository certify the physical build?'],
  ['To accommodate joints and tune the initial geometry gently.','S0, joining 0 to 4.','No; geometry is numerically checked, physical build remains learner-tested.'],
  'A measured model or a documented unsuccessful attempt and diagnosis.')

L('Twist, symmetry and cable length',
  'Relate rotation to member lengths without assuming all twists are equilibria.',
  'At fixed radius R and height h, the corresponding-node cable length is sqrt(h²+2R²(1−cos α)). Our offset strut length is sqrt(h²+2R²(1−cos(α+120°))). Symmetry makes each family equal in length. Changing α changes geometry; it need not preserve an admissible self-stress for the same connectivity.',
  'For R=0.08 m and h=0.14 m, at α=0° each corresponding-node cable is 0.14 m. At α=30° it is approximately 0.14600 m. The 30° example has a valid analytic self-stress; the twist sweep checks other angles separately.',
  'Calculator or Python, member table; no physical retensioning is required.',
  ['Calculate the cable length at 0° and 30°.','Predict whether increasing h changes all member families.','Generate prism outputs at 30° and 45° using different output filenames.','Compare member lengths and nullspace dimensions.','Separate geometric feasibility from force-equilibrium feasibility in your notes.'],
  'Triangle edges depend on radius only; cross and strut spans depend on height and twist.',
  'A visually attractive twist may have no nonzero self-stress in this ideal free framework.',
  ['Do triangle edges depend on height?','What is C0’s span at zero twist?','Does a new geometry automatically balance?'],
  ['No, when radius is fixed.','0.14 m in the example.','No; solve and check forces.'],
  'Two geometry tables with an equilibrium distinction.', 'prism')

L('Repeatable assembly and joints',
  'Turn a successful assembly into instructions another person can follow.',
  'Repeatability depends on component identification, joint consistency and inspection points. A procedure should identify an observable check after each action. Photographs help, but labels and measured spans carry the information. Record assembly time separately from time spent learning the method.',
  '“Attach S0 to nodes 0 and 4, then check both labels” is reproducible. “Connect the long rod here” is ambiguous when three rods look alike. If the two builds have heights 140 and 148 mm, inspect cable settings and endpoint definitions before claiming equivalence.',
  'Labeled kit, ruler, timer, sample joint and private photo record.',
  ['Write a numbered assembly procedure with one check per step.','Add node labels and a joint close-up.','Disassemble only when the low-tension model can be released safely.','Rebuild using the procedure, or ask a partner to use it.','Compare three dimensions, time and any interpretation questions.'],
  'The second build exposes missing instructions and produces a measurable comparison.',
  'A fast build with unsecured joints is not a successful repeat. Avoid measuring only the best attempt.',
  ['What makes a step unambiguous?','Why compare dimensions?','Should questions during assembly be recorded?'],
  ['Named parts, endpoint labels and an observable check.','To test whether the outcome was reproduced.','Yes; they reveal instructions needing improvement.'],
  'Revision 2 assembly instructions and repeatability table.')

L('Units and vectors',
  'Convert dimensions to SI and compute a member direction.',
  'A vector has components and direction. For endpoints a and b, d=b−a; length is sqrt(dx²+dy²+dz²); unit direction is d/length. Mass in kg and force in N differ by acceleration: weight W=mg. Unit conversion must precede substitution into SI equations.',
  'For a=(0,0,0) m and b=(0.03,0.04,0) m, d=(0.03,0.04,0), length=0.05 m and unit direction=(0.6,0.8,0). A 2 N tension acting from a toward b has components (1.2,1.6,0) N.',
  'Calculator, paper; optional Python console.',
  ['Convert 80,140 and 200 mm to m.','Compute the worked example length and unit vector.','Check that the unit-vector squared components sum to one.','Convert 100 g to kg and calculate its weight using g=9.81.','Draw the vector and annotate units on every number.'],
  'The example force components combine to magnitude 2 N.',
  'Do not enter mm into an equation expecting m. A zero-length member has no defined unit direction.',
  ['What is 140 mm in m?','What is the example unit vector?','What is 100 g’s weight?'],
  ['0.14 m.','(0.6,0.8,0).','Approximately 0.981 N.'],
  'Unit conversions, vector calculation and labeled drawing.')

L('Free-body diagrams',
  'Draw a selected object with all external forces and no hidden support assumptions.',
  'Choose the body before drawing forces. A cable pulls the isolated node toward its other endpoint. A compressed strut pushes the isolated node away from its other endpoint. Draw reactions only where a support acts on the chosen body. Internal members disappear when isolating the entire structure, but their forces appear when isolating one node.',
  'For a node connected to a horizontal cable on its right, that cable contributes a rightward force. A compressed strut ending above the node pushes away from its far endpoint, with a downward component. Gravity and a support reaction must be included when present.',
  'Paper, ruler and prism topology drawing.',
  ['Draw boundaries for one member, one node and the whole model.','At node 0, draw the four member directions using the supplied coordinates.','Assign tensile arrows to cables and compressive arrows to the strut.','Add external forces only for the physical supported case.','Check whether any reaction has been assumed without a real support.'],
  'Different isolated bodies legitimately have different external-force sets.',
  'Do not copy the whole-structure reaction into every node diagram. Each support acts at a particular contact.',
  ['Where does cable tension point on a node?','Do internal member forces remain on the whole-body diagram?','Why define a boundary?'],
  ['Toward its other endpoint.','No, internal force pairs cancel.','It determines which forces are external.'],
  'Three free-body diagrams with a written sign convention.')

L('Force and moment balance',
  'Solve a simple supported load and understand why force balance is insufficient alone.',
  'For a static rigid body, summed forces and summed moments must vanish. Moment depends on force and perpendicular lever arm. A simple two-support example isolates the principle before using it in complicated geometry. This calculation does not establish joint capacity or geometric stability.',
  'A 2 N downward load acts 0.15 m from the left support of a 0.30 m beam. Moments about the left support give Rright×0.30−2×0.15=0, hence Rright=1 N. Vertical balance gives Rleft=1 N. Moving the load to 0.10 m gives Rright=0.667 N and Rleft=1.333 N.',
  'Paper, calculator and ruler; use sketches rather than adding a real beam load.',
  ['Draw the two-support system and label distances.','Solve both load positions and check vertical force totals.','Verify moments about the right support as an independent check.','Explain which symmetry assumption justified equal reactions in the first case.','Write why these equations do not certify a tensegrity prism.'],
  'Reaction distribution changes when the load position changes.',
  'A force outside the support span may require uplift resistance; do not assume contacts can pull.',
  ['What is moment’s SI unit?','Why are the first reactions equal?','Is force balance alone enough for a rigid-body statics check?'],
  ['N·m.','The load is centered between equivalent supports.','No; moments must balance too.'],
  'Two solved support examples with independent moment checks.')

L('Nodal equilibrium and self-stress',
  'Verify a nonzero balanced internal force-density state in the ideal prism.',
  'For member i, force density q_i=F_i/L_i. At a node, sum q_i(x_other−x_node)=0 in the unloaded free case. At 30° twist our analytic state uses ring densities 1/√3 N/m, cross densities 1 N/m and strut densities −1 N/m. The scale can vary; real material and stability limits remain separate.',
  'A ring length 0.13856 m with q=1/√3 N/m carries approximately 0.08 N tension. A 0.14600 m cross cable with q=1 N/m carries approximately 0.14600 N. These forces differ despite symmetric families. The code evaluates residuals at all six nodes.',
  'Calculator or Python and the prism output.',
  ['Run the prism lab at its default geometry.','Find example_force_density and example_member_force_N in the output.','Check one F=qL multiplication by hand.','Explain why the negative entries correspond to the intended struts.','Inspect the maximum residual and describe what its small value does and does not show.'],
  'The ideal analytic state balances to floating-point precision and has cable-positive/strut-negative signs.',
  'q is N/m, not N. A small residual is an equilibrium check, not proof of prestress stability.',
  ['How is force density defined?','Why is a strut density negative?','What remains after checking equilibrium?'],
  ['Force divided by member length.','Compression uses the stated negative sign.','Stability, constitutive behavior, capacities, joints and supported load cases.'],
  'A hand calculation, solver output and limitations statement.', 'prism')

L('Cable stiffness and stretch',
  'Estimate a local stiffness from a small force–extension record.',
  'For a locally linear axial member, stiffness k≈ΔF/ΔL in N/m. For a homogeneous ideal member k=EA/L, where E is elastic modulus, A is area and L is reference length. Real cord, knots and elastic bands may show nonlinear response and hysteresis. Distinguish stiffness from strength and from prestress.',
  'An illustrative sample extends 2 mm at 0.2 N and 4 mm at 0.4 N. The slope over that interval is (0.4−0.2)/(0.004−0.002)=100 N/m. This is a local estimate, not a breaking-load rating.',
  'Illustrative dataset examples/cable_extension.csv; optional small supervised test with a low-force spring scale and contained tray.',
  ['Plot force against extension from the sample dataset.','Calculate the slope over two intervals.','Predict force at 3 mm extension under the local linear assumption.','If testing a real sample, use small increments and stop on slip or damage.','Record loading and unloading separately and compare with the ideal law.'],
  'The synthetic linear data yields 100 N/m; real samples may show differing slopes and hysteresis.',
  'Do not extrapolate a low-load slope to failure or substitute knot movement for material extension.',
  ['What are stiffness units?','Is stiffness the same as strength?','What force is predicted at 3 mm?'],
  ['N/m.','No; strength concerns failure capacity.','0.3 N for the stated zero-offset linear example.'],
  'A force–extension plot/table and scope of the stiffness estimate.', 'spring')

L('Strut buckling',
  'Use an ideal buckling equation to explore length sensitivity.',
  'Euler’s ideal elastic column model gives Pcr=π²EI/(KL)². E is modulus in Pa, I the cross-section second moment in m⁴, L the length in m and K an effective-length factor. It assumes a slender, straight column with idealized end conditions. Actual failure may occur earlier because of imperfections, joints or material limits.',
  'Using hypothetical E=2×10⁹ Pa, I=10⁻¹⁰ m⁴, L=0.20 m and K=1 gives approximately 49.35 N. Doubling L gives about 12.34 N, one quarter. These inputs are illustrative, not properties or a rating for your craft sticks.',
  'Calculator or Python; no physical failure test required.',
  ['Run the default buckling lab and reproduce the value by hand.','Run it at length 0.4 m; calculate the ratio.','Change K to 2 and explain the result.','List three reasons a physical strut may fail below the ideal value.','Label your table “hypothetical ideal column,” not “safe load.”'],
  'Longer effective length sharply reduces the ideal buckling load.',
  'Do not use the result as a allowable load or deliberately load a classroom strut to collapse.',
  ['What happens when length doubles?','What does I measure?','Is Pcr a complete safe-load calculation?'],
  ['The ideal load becomes one quarter.','Cross-section bending geometry, in m⁴.','No; assumptions, failure modes and margins need review.'],
  'A parameter table and three model limitations.', 'buckling')

L('Joints, slip and creep',
  'Separate immediate joint movement from time-dependent deformation.',
  'Slip changes the attachment position; creep is time-dependent deformation under sustained load. Both change geometry and prestress. A witness mark across a joint helps identify slip, while a span measurement over time captures total movement. More than one cause can act at once, so observations should not force a single diagnosis.',
  'A span changes from 140 to 142 mm over ten minutes. If the witness mark also moves 2 mm, joint slip is plausible. If the mark stays fixed, cord or elastic creep remains plausible, along with measurement error. One measurement alone cannot distinguish them.',
  'Low-tension sample connection, tape witness mark, ruler and timer; no added hanging masses.',
  ['Mark both sides of one attachment and record initial span.','Keep a small, unchanged initial tension and note the method.','Read span and marks at 0,2,5 and 10 minutes.','Release tension gently and record whether length recovers.','Compare the observations with competing explanations.'],
  'The time record can reveal motion at the joint, material deformation or inconclusive change.',
  'Keep ambient conditions and measuring method consistent. Stop if movement becomes sudden.',
  ['What does a witness mark reveal?','What distinguishes creep from instant elastic extension?','Can a 2 mm change alone identify the cause?'],
  ['Relative slip at an attachment.','Creep evolves with time under sustained load.','No; inspect joints, material and measurement method.'],
  'A span-versus-time record and diagnosis with uncertainty.')

L('Corrosion, fatigue and inspection',
  'Create an inspection plan tied to failure modes.',
  'Corrosion can reduce material section or damage connections; fatigue involves damage under repeated cycles. A new model’s single static test says little about long-term behavior. Inspection should name the component, possible defect, method, action and responsible person. Do not infer outdoor suitability from an indoor classroom kit.',
  'For C0, a plausible mode is cord fraying near a sharp attachment. Inspection: look for broken fibers before each classroom session. Action: release the model safely, replace the component and retest the joint. This is more useful than “check the structure.”',
  'Prism drawing, sample undamaged cord, templates/inspection.csv.',
  ['List one plausible failure mode for cable, strut and joint.','For each, write a detectable sign and inspection method.','Set a pre-session classroom check and a response to defects.','Explain what additional evidence outdoor salt, heat and UV exposure would require.','Assign an owner for the inspection record.'],
  'Every identified defect has an action rather than an observation without follow-up.',
  'Visual inspection cannot detect every internal defect or predict service life. No lifetime rating is provided.',
  ['What is fatigue related to?','Does one static test establish durability?','What must an inspection include besides a defect?'],
  ['Repeated loading cycles and material response.','No.','A method, decision/action and accountable owner.'],
  'Three-component inspection plan with actions.')

L('Coordinates and member lengths',
  'Generate geometry and independently check its dimensions.',
  'Coordinates give a precise geometric model. Our bottom triangle lies at z=0; the top at z=h, rotated by α. Node radii are measured from the central axis, not between adjacent nodes. Member length is Euclidean distance between its endpoint coordinates. The drawing uses projection, so visual lengths are not measurement values.',
  'A triangle on a circle of radius R has side √3R. At R=0.08 m the edge is 0.138564 m. Both bottom and top rings share this value. Setting h=0.16 m changes cross/strut lengths while leaving ring edges unchanged.',
  'Python 3.10+, calculator and prism drawing; manual calculation alternative permitted.',
  ['Generate the default prism JSON.','Calculate the bottom ring length from √3R.','Check node z coordinates and radial distances.','Generate a second geometry with --height 0.16 and a separate output path.','Compare each member family and note projection versus true length.'],
  'All equivalent members agree and independently checked distances match the code.',
  'Geometry output is a mathematical model, not a fabrication certificate. Units and node definitions must travel with it.',
  ['What does radius mean here?','How long is a triangle edge?','Why not measure the projected diagram?'],
  ['Distance from axis to a node in each triangle.','√3R.','Projection distorts apparent lengths.'],
  'Two saved geometries and independent distance checks.', 'prism')

L('Equilibrium matrices',
  'Read how member connectivity becomes a linear equilibrium system.',
  'The force-density matrix A has three rows per node and one column per member. At endpoint a the member column contains x_b−x_a; at b it contains the negative. Thus A q=0 represents free unloaded self-stress. This differs from a unit-direction matrix acting on axial forces F. A nontrivial nullspace may describe balanced internal stress, but admissible signs and stability still matter.',
  'Six nodes give 18 rows and twelve members give 12 columns. Our 30° prism has a one-dimensional self-stress nullspace in the chosen numerical tolerance. Multiplying any basis vector by a scalar retains equilibrium; its signs must match cables and struts.',
  'Python, tensegrity/models.py and default prism output.',
  ['Read equilibrium_matrix and identify endpoint row indices.','Inspect one column and verify that endpoint entries cancel.','Run the prism lab and inspect its nullspace basis.','Multiply the analytic q by 2 and verify residual scaling remains near zero.','State why a solver’s tolerance and unit scaling matter.'],
  'The independent analytic vector agrees with a numerical nullspace up to scale and sign.',
  'Do not confuse numerical rank with exact symbolic proof, especially near the special twist angle.',
  ['What are A’s dimensions?','What multiplies this A: q or F?','Can any nullspace vector be used physically?'],
  ['18×12.','Force density q.','No; sign constraints and other physical checks apply.'],
  'A matrix-column explanation and residual verification.', 'prism')

L('Constrained form-finding',
  'Explore a constrained geometry search and identify feasible equilibrium.',
  'Form-finding seeks geometry compatible with chosen connectivity and force/material constraints. Our introductory lab restricts radius and height and varies only twist; it is not a general nonlinear design optimizer. The reference analytic q balances at 30° for this topology. Away from that angle, residual grows and the numerical nullspace usually becomes trivial.',
  'At 30°, y components from corresponding cable and offset strut cancel because sin30°=sin150°. Their x components balance the two ring cables when qring=qcross/√3. This explains the special geometry rather than merely selecting the prettiest rendering.',
  'Python or calculator; no physical high-tension geometry search.',
  ['Run the sweep lab for the supplied nine twist angles.','Locate the angle with a nonzero nullspace and a near-zero reference residual.','Explain the y-component cancellation at 30°.','Name constraints missing from the sweep: material rest lengths, external loads and stability.','Describe what evidence a general solver would need before acceptance.'],
  'The constrained scan reveals a special equilibrium and separates it from arbitrary geometric variants.',
  'A small sample scan does not prove that no other equilibrium geometry exists outside its range or topology.',
  ['Which variable is searched?','Does the lab optimize every node?','What must be checked beyond residual?'],
  ['Top-triangle twist.','No; radius and height are fixed.','Force signs, mechanisms/stability, constitutive laws, joints and loads.'],
  'A twist-sweep table with a feasibility interpretation.', 'sweep')

L('Sensitivity and physical validation',
  'Compare measured geometry with predictions and diagnose discrepancies.',
  'Sensitivity asks how much an output changes when an input changes. Validation compares a model with independent physical observations; verification checks correct implementation of its equations. A code test can verify ring length, but it does not validate a real joint. Separate numerical tolerances from instrument uncertainty.',
  'An ideal ring span is 138.56 mm; a measured one is 141 mm. Absolute difference is 2.44 mm and relative difference is about 1.76%. A knot-center definition, stretching or radius mismatch may explain it. A small force residual does not remove these differences.',
  'Default digital geometry, physical model or provided illustrative measurement table, ruler.',
  ['Change radius by +1% and predict ring length change.','Run the geometry and verify that proportional change.','Measure three spans of a physical model, or explicitly use synthetic values.','Compute absolute and relative differences from prediction.','Choose one plausible cause and a measurement that could discriminate it.'],
  'The geometry response is predictable; physical agreement depends on actual dimensions and assumptions.',
  'Never label synthetic comparison data as experimental validation. Do not tune all inputs until agreement and then call it independent validation.',
  ['What is verification?','What is validation?','What is the example relative difference?'],
  ['Checking implementation against equations or known results.','Comparing with independent physical observations.','About 1.76%.'],
  'Sensitivity result and measured/predicted error table.')

L('Vibration and damping',
  'Distinguish stiffness, inertia and damping through a one-degree-of-freedom example.',
  'A simple oscillator follows m ẍ+c ẋ+k x=0. Mass stores kinetic energy, stiffness stores elastic energy and damping dissipates energy. Its undamped natural angular frequency is sqrt(k/m). This model teaches dynamics but does not represent every node or mode of a tensegrity structure.',
  'For m=1 kg and k=4 N/m, natural angular frequency is 2 rad/s, about 0.318 Hz. With c=0, ideal total energy stays constant; with c=0.4 N·s/m, it decays. The supplied RK4 integrator checks numerical behavior over small time steps.',
  'Python or supplied example oscillator table; optional ruler and video of a gently disturbed tabletop model.',
  ['Calculate the example natural frequency.','Run the oscillator with damping 0 and 0.4, saving to different files.','Compare displacement peaks and energy columns.','If observing a model, gently disturb it without adding loads; record motion without claiming a fitted full model.','Explain one reason measured oscillation differs from the one-DOF idealization.'],
  'Undamped energy varies only by small numerical error; positive damping reduces energy.',
  'Numerical time-step error can resemble damping. Multiple structural modes cannot be inferred from one trace alone.',
  ['What does damping do to energy?','What is sqrt(k/m)?','Is this a full tensegrity dynamic solver?'],
  ['It dissipates mechanical energy in this model.','Undamped natural angular frequency in rad/s.','No; it is a one-degree-of-freedom teaching example.'],
  'Two oscillator traces and a model-scope explanation.', 'oscillator')

L('Impacts and recovery',
  'Define a repeatable low-energy disturbance and measure recovery.',
  'Resilience must be tied to a specific disturbance and observable response. Returning to a similar shape does not establish lack of damage. Impact energy depends on mass and velocity, or mgh for an ideal drop. Our classroom exercise uses a small controlled displacement and release rather than dropping a structure.',
  'For a linear k=4 N/m spring displaced 0.01 m, stored energy is ½kx²=0.0002 J. Doubling displacement quadruples this ideal energy. A real model can have slack cables, friction and several modes, so the equation is only an illustrative baseline.',
  'Low-tension tabletop model, ruler, tray, timer or camera; alternative: oscillator lab.',
  ['Record initial geometry and inspect joints.','Set a very small displacement that stays within gentle handling; record it.','Release without pushing and record settling behavior.','Repeat three times after inspection, stopping on slip or damage.','Compare final span and joint witness marks with the initial record.'],
  'Results separate motion recovery from geometry retention and connection condition.',
  'Do not drop the model or claim shock resistance from a hand disturbance. If release is unpredictable, use simulation instead.',
  ['What happens to ideal energy if displacement doubles?','Does shape recovery prove no damage?','What should be inspected after a trial?'],
  ['It becomes four times larger.','No.','Connections, struts, cables and measured geometry.'],
  'A disturbance protocol and three-trial recovery table.')

L('Wind and changing loads',
  'Explore wind-load scaling and identify missing full-scale information.',
  'A simplified drag estimate is F=½ρV²CdA. Density ρ is kg/m³, speed V is m/s, coefficient Cd dimensionless and area A m². Real wind loading includes pressure distribution, uplift, gusts, direction, shielding and dynamic response. This lesson explores scaling; it does not supply Singapore design wind loads.',
  'For illustrative ρ=1.2, Cd=1, A=0.1 m² and V=5 m/s, F=1.5 N. At 10 m/s it is 6 N. Doubling speed quadruples the simplified force. Cd=1 is an assumed example, not a measured panel coefficient.',
  'Calculator and a dummy-panel sketch; no wind machine required.',
  ['Calculate force at 5,10 and 15 m/s using the stated assumptions.','Change area by a factor of two and calculate the effect.','Draw force directions for uplift and lateral loading.','List missing site and aerodynamic inputs for a rooftop canopy.','Write a professional-review question instead of claiming the prototype is storm-proof.'],
  'Quadratic speed dependence is apparent and missing assumptions are explicit.',
  'A desk-fan trial cannot be extrapolated to severe storms without similarity and load analysis.',
  ['How does force scale with speed here?','Is Cd=1 universal?','Does this give approved design loads?'],
  ['With V².','No; it depends on shape and flow.','No; site-specific design and current requirements need qualified review.'],
  'An illustrative load table and site-information request list.')

L('Damaged-member scenarios',
  'Assess topology changes without deliberately causing an energetic failure.',
  'Removing a member changes the force-equilibrium system and possible mechanisms. A prior self-stress vector cannot simply be reused. Redundancy means a system can retain required function after a defined failure, not merely that it has many components. Review damage in the digital model before considering physical handling.',
  'Delete C0 from the 30° prism member list, rebuild A and compute its nullspace. In this ideal example the original nonzero self-stress is lost. That finding concerns this topology and unloaded idealization; it is not a general result for every tensegrity.',
  'Python console, models.py and node/member schedule; physical model observation is optional.',
  ['Copy the short damaged-member example in labs/README.md.','Inspect the original matrix and self-stress dimension.','Remove C0 and repeat the calculation.','Explain why unchanged appearance would not prove retained capability.','Write a detect–isolate–repair–recheck procedure for a frayed C0.'],
  'The numerical result illustrates how one missing member changes the equilibrium problem.',
  'Do not cut a loaded cable. Physical removal occurs only after all tension is safely released.',
  ['Can you reuse the original force vector?','What does redundancy require?','When may a damaged cable be removed physically?'],
  ['No; connectivity and equilibrium have changed.','Evidence of retained function after a specified failure.','After safe release of tension and support of the model.'],
  'Original/damaged comparison and a repair procedure.')

L('Panel area, orientation and shading',
  'Separate solar conversion efficiency from energy yield and support geometry.',
  'A support can change orientation, shading and operating conditions without changing the cell technology. Power P=VI requires simultaneous voltage/current at the same loaded operating point. Conversion efficiency relates electrical power to incident solar power over area; yield is integrated energy over time. This course tests support tradeoffs rather than assuming tensegrity increases efficiency.',
  'At a loaded 5 V and 0.1 A, power is 0.5 W. Over two minutes of constant output this is 0.01667 Wh. Our sample fluctuating record gives approximately 0.01833 Wh by trapezoidal integration. Open-circuit V and short-circuit I must not be multiplied together as operating power.',
  'Paper dummy panel, angle ruler; optional small educational low-voltage panel, suitable load and meters used according to instructions.',
  ['Measure dummy-panel area and choose a repeatable angle reference.','Calculate the constant-power example.','Run the solar lab on the synthetic readings.','Draw possible shadows from struts and cables at two orientations.','Write which measurements would separate orientation benefits from actual conversion efficiency.'],
  'The learner reports energy over a defined interval and identifies shading as a measurable mechanism.',
  'Do not connect to household electricity or improvise grid wiring. Synthetic readings do not establish real solar performance.',
  ['What readings are required for operating power?','Does structure shape inherently change cell efficiency?','What are energy units here?'],
  ['Simultaneous loaded V and I at the same operating point.','No; effects require identified mechanisms and measurements.','Wh.'],
  'Panel/shadow sketch and a checked power–energy calculation.', 'solar')

L('Rooftop load paths and maintenance',
  'Turn a rooftop idea into a reviewable concept with access and load-path questions.',
  'A rooftop installation transfers gravity, wind and other actions to the building through attachments or ballast. It also affects waterproofing, drainage, access, fire-related considerations and maintenance. A tabletop model is a communication tool, not evidence that an HDB roof can accept an installation. Requirements depend on the actual site and current authorities.',
  'A concept places a sculpture across a roof access route. Even if its ideal members balance, it fails the maintenance-use case. Moving it requires rechecking attachment positions, shading and load paths; aesthetics alone do not determine feasibility.',
  'A fictional roof plan, paper and templates/site-review.md. No roof access is part of this lesson.',
  ['Draw a fictional roof with parapet, drain and access route.','Place a dummy concept and mark gravity/uplift transfer points.','Draw the panel-replacement route and a way to inspect joints.','List missing roof, attachment, electrical and ownership information.','Mark review gates and responsible professional roles without inventing approvals.'],
  'The concept includes access, drainage and structural information needs as first-class design inputs.',
  'Never visit or install on a roof as a classroom exercise. Do not invent current statutory requirements or approval status.',
  ['Where must rooftop forces go?','Does a tabletop model establish roof capacity?','Name a nonstructural maintenance consideration.'],
  ['Through defined attachments/supports into the building.','No.','Access, drainage, waterproofing or safe panel replacement.'],
  'An annotated fictional roof concept and review checklist.')

L('Floating systems and moorings',
  'Explain buoyancy and station-keeping as additional systems beyond tensegrity.',
  'A floating solar concept needs buoyancy, stability, moorings, electrical protection and maintenance. Tensegrity can be a support geometry but does not supply flotation by itself. For static buoyancy, displaced fluid weight balances total weight. Moorings manage movement and environmental loads; they are not represented by a free self-stress model.',
  'A 1 kg assembly floating in fresh water of density 1000 kg/m³ displaces about 0.001 m³, or one liter, at balance. Practical flotation needs allowance for reserve buoyancy and stability; one liter of nominal displacement is not a complete float design.',
  'Paper concept, calculator and a fictional pond plan. Water testing is not required.',
  ['Calculate displacement for illustrative total masses 1 and 2 kg.','Draw floats, support geometry, mooring points and electrical route as separate systems.','Consider tilt, water-level changes, debris and access for repair.','List conditions not captured by the tabletop prism.','Prepare a basin-test proposal for qualified review rather than placing equipment on open water.'],
  'The diagram separates structure from flotation and station-keeping.',
  'Do not place electrical prototypes on public water or work near water without a suitable supervised plan.',
  ['Does tensegrity provide buoyancy automatically?','How much water does 1 kg displace in the example?','What do moorings control?'],
  ['No.','About one liter of fresh water.','Station-keeping and environmental movement/load transfer.'],
  'A system diagram and displacement calculation.')

L('Compare against a conventional frame',
  'Design a fair baseline comparison and accept tradeoffs.',
  'A comparison needs a common task and comparable boundary conditions. Match panel area, load, height/angle and available footprint where possible. Record mass, cost, assembly time, deflection and maintenance access. If two objectives conflict, report them separately rather than hiding them in an arbitrary total score.',
  'Synthetic results: tensegrity mass 120 g and assembly 25 minutes; frame mass 180 g and assembly 8 minutes. The tensegrity example is lighter but slower to build. These numbers are teaching data, not evidence of a general advantage.',
  'Two tabletop dummy-panel supports or illustrative data; templates/comparison.csv.',
  ['Define the same task for both concepts.','Choose three metrics and measurement methods before observing results.','Record unmatched dimensions or materials as confounders.','Measure or clearly label synthetic values, retaining repeat trials.','Write a recommendation tied to the intended user and maintenance conditions.'],
  'The recommendation states what improved, what worsened and how certain the result is.',
  'Avoid comparing a delicate miniature with an overbuilt frame and presenting the mass difference as universal superiority.',
  ['What should be fixed before testing?','What is a confounder?','Can a negative result be useful?'],
  ['Task, baseline, metrics and methods.','An uncontrolled difference that may explain the outcome.','Yes; it helps select a suitable design.'],
  'A baseline comparison with tradeoffs and limitations.')

L('Displacement and force measurement',
  'Choose a measurement method for a defined structural question.',
  'Displacement, force and angle are different variables and need different references. A ruler can measure a span; a calibrated scale can estimate tension; a sensor only measures what its placement and calibration allow. Manual measurement is a valid route when it answers the question. A sensor count is not itself evidence of better understanding.',
  'Question: does the top tilt after rebuilding? Measure two top-node heights relative to the same flat table. A 3 mm height difference over a 140 mm horizontal span gives an approximate small tilt of atan(3/140)≈1.23°. This is a two-point estimate, not the full plane orientation.',
  'Ruler, stable table and labeled model; optional low-force gauge or sensor.',
  ['State the variable and reference frame.','Choose two points and a consistent measuring method.','Measure three times with the instrument reset.','Compute the example tilt and compare resolution to expected motion.','If using a sensor, draw its mounting and how it affects the model.'],
  'The chosen instrument can resolve the intended change, or its limitation is reported.',
  'Attaching a sensor adds mass and stiffness. Do not call a voltage reading a force without calibration.',
  ['What reference is needed for height?','Can voltage alone be read as force?','What is the example approximate tilt?'],
  ['A defined stable datum such as the same tabletop.','No; use a validated calibration relationship.','Approximately 1.23°.'],
  'A measurement plan and three-repeat readings.')

L('Data quality and calibration',
  'Fit and independently check a simple calibration.',
  'Calibration relates a reading to known reference values over a stated range. A two-point line can estimate offset and slope; extra independent points test its adequacy. Keep raw readings, units, timestamp and calibration version. Missing data is not zero and should not be silently replaced by a plausible value.',
  'A hypothetical gauge gives 10 counts at 0 N and 210 counts at 1 N. F=(counts−10)/200 N. An independent 0.5 N check should read 110 counts ideally. If it reads 118, the prediction is 0.54 N, an error of 0.04 N.',
  'Paper calibration data or an appropriate low-force sensor and reference; no unverified force application needed.',
  ['Calculate the slope and offset from the two reference points.','Predict the third point before revealing its example reading.','Compute the independent check error.','Set a course-specific acceptable error based on the intended measurement, not a universal threshold.','Log calibration range, version and missing-data handling.'],
  'The record distinguishes fitted points from independent checks.',
  'A high-precision fit to two points says nothing about hysteresis, drift or nonlinear behavior outside that range.',
  ['What is the example slope in counts/N?','Is a fitted point an independent check?','What should missing data become?'],
  ['200 counts/N.','No.','An explicit missing entry with a reason, not zero.'],
  'Calibration equation, independent error and metadata record.')

L('Bounded cable adjustment',
  'Inspect a simulated feedback rule before considering hardware.',
  'A feedback rule changes a command based on error. Our mock controller limits the command change and clamps the commanded cable length between bounds. The mock reading equals command length, so this is a toy plant, not a prism controller. Real hardware also needs force limits, sensor validation, emergency stop and review of failure modes.',
  'At current length 0.150 m, target 0.160 m and gain 0.2, raw change is 0.002 m. With maximum step 0.001 m, next command is 0.151 m. A command beyond the upper bound is clamped; this software bound does not physically prevent excess tension.',
  'Python and the controller lab; no motors or hardware connected.',
  ['Calculate the first bounded step by hand.','Run the controller lab and compare its first row.','Use the API to test current length at the upper bound.','List consequences of a stuck sensor and a wrong sign of feedback.','Draft hardware-review conditions without implementing a physical actuator.'],
  'The simulated command approaches the target within stated bounds and has limited step size.',
  'Do not use the toy controller on hardware. Length bounds alone do not bound cable force.',
  ['What is the first next command?','Is the mock sensor realistic?','Do command bounds guarantee safe force?'],
  ['0.151 m.','No; it directly reports commanded length.','No.'],
  'A hand-checked controller trace and failure-case list.', 'controller')

L('AI-assisted analysis and inspection',
  'Use AI for explanation while retaining independent checks and evidence.',
  'AI can suggest calculations, summarize notes and identify possible defects in images. It can also invent measurements, misunderstand topology or miss a defect. Treat outputs as proposals: verify units, endpoints, equations and facts against evidence. Ground every completion decision in work the learner actually supplies.',
  'An AI says a 140 mm member is 1.4 m and produces plausible forces. A unit check catches the factor-of-ten error before interpreting the result. An AI photo comment “joint looks secure” cannot establish pullout strength or hidden damage.',
  'A completed experiment record, optional AI assistant; no external service is required.',
  ['Give an assistant a non-identifying member table or use the supplied faulty-example scenario.','Ask it to explain the load path and list assumptions.','Independently verify one unit conversion and one force calculation.','Classify each statement as observed, calculated, inferred or unsupported.','Revise the report while retaining disagreements and missing evidence.'],
  'Useful explanation survives checks; unsupported confidence is removed.',
  'Do not upload personal learner records or rely on image recognition for structural approval.',
  ['What is the correct conversion of 140 mm?','Can a photo prove joint capacity?','Who provides experimental evidence?'],
  ['0.14 m.','No.','The learner or experimenter, with traceable measurements.'],
  'An AI-output review with independent corrections.')

L('Visual task sequences',
  'Produce a predictable assembly sequence with observable checks.',
  'A visual sequence reduces ambiguity by showing the part, action and completion cue. Color should be supported by numbers or shapes because color perception and printing differ. Use one action per card, allow a learner to pause, and show what a correct endpoint connection looks like. The method is an educational option, not a universal intervention.',
  'Card: “Find S0; connect nodes 0 and 4; check both node numbers; place the finished card in DONE.” This is more precise than showing an unlabeled photograph of a partly built prism.',
  'Paper cards, labeled components and templates/task-card.md.',
  ['Choose one short assembly segment with three or four actions.','Make a card for each action with labels and completion cue.','Include a help request and pause option.','Try the cards with a willing learner or peer using their preferred supports.','Record where the sequence was unclear and revise one card.'],
  'The learner can identify what comes next and when a step is finished.',
  'Do not remove helpful support just to score independence. Avoid assumptions about autism based on diagnosis alone.',
  ['Why combine color with labels?','What is a completion cue?','Should every learner use the same support?'],
  ['Labels remain meaningful without color.','An observable sign that the action is done correctly.','No; choose supports with the individual.'],
  'A tested short task-card sequence.')

L('Sensory and motor adaptations',
  'Adapt the activity while preserving its learning objective.',
  'Access can involve quieter space, predictable instructions, pre-cut parts, larger labels, assembly jigs, breaks or a partner. Ask what the learner prefers rather than treating a diagnosis as a complete profile. Separate the mechanics objective from unnecessary dexterity demands. Pointing or demonstration can show understanding without a spoken presentation.',
  'Objective: identify tension members. A learner who finds knots difficult can use a preassembled model and point to labeled cables. Knot-tying performance should not determine the score for force identification.',
  'Activity plan, support-choice cards and a preassembled model if available.',
  ['Name one core learning objective and one nonessential task demand.','Offer two support choices and a way to request a change.','Provide a quiet or low-stimulation alternative where possible.','Let the learner demonstrate understanding in a chosen form.','Record which supports helped without collecting unnecessary diagnostic information.'],
  'Assessment captures the intended concept while access choices remain flexible.',
  'Do not claim this course treats autism or guarantees therapeutic benefit. Institutional pilots require educator and participant involvement.',
  ['Does knot difficulty imply poor structural understanding?','Name an alternative to a spoken answer.','Who should help select adaptations?'],
  ['No.','Pointing, drawing or demonstration.','The learner, with relevant educators/support people.'],
  'An adapted activity with a concept-aligned assessment.')

L('Assembly quality and inspection skills',
  'Demonstrate a practical quality-control task with traceable records.',
  'Quality work compares a component with a specified criterion. A classroom criterion must be explicit and achievable with the instrument. Sorting, labeling, reading instructions and documenting defects are transferable skills, but this activity does not establish occupational competence or promise employment. Use simulated defects instead of creating hazardous ones.',
  'A practice instruction requires a 140±2 mm span, measured with a 1 mm ruler. A 139 mm sample passes that stated classroom criterion; a 145 mm sample is held for review. These tolerances are educational choices, not engineering specifications.',
  'Three labeled cord samples or drawings with 139,140 and 145 mm spans; ruler and inspection form.',
  ['Read the written span criterion aloud or show it visually.','Measure each sample and record the value.','Classify pass or hold without hiding borderline uncertainty.','Describe the defect and the required review or adjustment.','Have another person audit one record against the sample.'],
  'The record identifies component, criterion, reading and action.',
  'Do not confuse a classroom tolerance with an approved construction tolerance or accredited technician qualification.',
  ['Does 139 mm pass the example criterion?','What action applies to 145 mm?','Does this promise employment?'],
  ['Yes.','Hold for review/adjustment.','No; it records a demonstrated practice skill.'],
  'Three inspection entries and one audited record.')

L('Facilitator practice and feedback',
  'Deliver a short session and improve it from learner evidence.',
  'Facilitation involves preparation, explanation, support and observation. Feedback should describe what worked or remained unclear rather than rank the learner’s worth. Ask permission before recording a session and avoid identifying public portfolios. A session is successful when its objective is demonstrated with suitable support, not merely when time expires.',
  'A learner labels three cables correctly but cannot explain slack. Feedback: “Your labels match the model; let us test what happens when the string shortens.” This names evidence and a next action rather than saying “you do not understand.”',
  'A 15-minute plan, simple model, task cards and facilitator observation sheet.',
  ['Choose one objective from lesson 05 or 09.','Prepare a short explanation, activity and two teach-back questions.','Offer response and support choices.','Run the session with a willing peer or rehearse and label it as rehearsal.','Collect one clarity comment and revise the next session.'],
  'Feedback connects observed evidence to a concrete next step.',
  'Do not record an unperformed rehearsal as a completed learner session. Support needs are not moral failures.',
  ['What should feedback cite?','What makes the session complete?','How should rehearsal be labeled?'],
  ['Specific observed evidence.','The objective is demonstrated with appropriate support.','As rehearsal, not an actual learner outcome.'],
  'A session plan, observation and revised facilitation note.')

L('Resident needs and co-design',
  'Convert a community idea into requirements without inventing resident support.',
  'Co-design starts with users, constraints and ownership. A solar sculpture may be valued for shade, identity, learning or energy, and these goals can conflict. Separate actual feedback from assumptions. Use fictional stakeholder scenarios until real participation is arranged with consent; do not present simulated quotes as a survey.',
  'Fictional resident A values shade; maintenance staff need unobstructed access; resident B wants a familiar estate symbol. A design that meets the symbol request but blocks access fails an important requirement. Energy output alone cannot settle that conflict.',
  'Fictional stakeholder cards and templates/community-brief.md.',
  ['List three stakeholder roles and a plausible need for each.','Mark each need as assumption or actual feedback.','Translate needs into observable requirements, such as an unobstructed route.','Identify conflicts and one question to resolve each.','Propose a small tabletop co-design session with participation options.'],
  'The brief distinguishes stakeholder evidence from designer assumptions.',
  'Do not imply endorsement by HDB, NAC, Pathlight or residents when none was obtained.',
  ['What separates evidence from assumption?','Can user needs conflict?','What is a useful next step?'],
  ['Traceable feedback versus a designer’s hypothesis.','Yes; show and resolve tradeoffs.','A consent-based small co-design activity with defined questions.'],
  'A stakeholder/requirements table with evidence status.')

L('Sculpture identity and alternatives',
  'Develop distinct concepts and compare them against requirements.',
  'Alternatives should differ in a meaningful design choice, not just color. Compare a tensegrity sculpture, conventional canopy concept and educational display against the same requirements. Aesthetic preference can be recorded alongside maintenance, access and performance evidence. “One estate, one solar sculpture” is a design vision, not a requirement to use the same structure everywhere.',
  'Concept A emphasizes a compact educational prism; B a conventional support with local artwork; C an adjustable tabletop sculpture. A display-only site may prefer A, while a maintenance-limited setting may prefer B. Selection follows the task and evidence.',
  'Paper, stakeholder brief and a concept comparison table.',
  ['Sketch three concepts with different structural or use choices.','Annotate panel/dummy-panel area, public interaction and access.','Compare each with three requirements from lesson 41.','Mark feasibility questions rather than inventing answers.','Choose one for the next prototype and state why.'],
  'The selected concept has a defensible connection to the intended user and task.',
  'Do not disguise an untested architectural rendering as an approved or buildable design.',
  ['What makes alternatives meaningful?','Can aesthetics alone prove feasibility?','Must every estate use the same design?'],
  ['Different decisions affecting requirements or tradeoffs.','No.','No; the vision allows local identity and suitable alternatives.'],
  'Three concept sketches and selection reasoning.')

L('Cost, maintenance and ownership',
  'Estimate lifecycle responsibilities rather than purchase price alone.',
  'Costs include materials, assembly labor, inspections, replacements, access and end-of-life work. Use quantities and unit costs with source/date or explicitly assumed values. Ownership names who maintains records, decides repairs and pays. A volunteer project still consumes time and materials; donated work should not disappear from the estimate.',
  'Illustrative values: materials S$30, two assembly hours at an assumed S$15/hour and an assumed annual inspection cost S$10 produce S$60 initial resource cost and S$70 including one year of inspection. These are planning examples, not market prices.',
  'Bill-of-materials template, paper calculator and maintenance plan.',
  ['Enter quantities and actual or explicitly assumed unit costs.','Add assembly hours separately from materials.','Name likely replacement components and inspection work.','Assign an owner, maintainer and repair decision-maker.','Compare initial and lifecycle estimates with the baseline frame.'],
  'The estimate reveals assumptions and recurring work, not just component totals.',
  'Do not claim current Singapore prices without checking them. Never imply an organization has accepted ownership.',
  ['Why count donated hours?','What must a cost source include?','Who decides a repair?'],
  ['They are real resource use.','Origin/date or an explicit assumption label.','A named responsible role agreed in the plan.'],
  'A cost estimate and responsibility matrix.')

L('Trial brief and review gates',
  'Define a bounded trial with evidence-based go/no-go decisions.',
  'A trial is a controlled way to answer a question. It has scope, responsible people, stop conditions and an evidence requirement for progression. An indoor tabletop demonstration is a different stage from a public installation. Gates should make that distinction explicit instead of turning enthusiasm into assumed approval.',
  'Gate 1: tabletop model has secure joints and repeatable assembly. Gate 2: independent geometry/force checks documented. Gate 3: any full-scale proposal receives qualified site-specific review. Passing gates 1–2 does not automatically pass gate 3.',
  'Templates/site-review.md and completed concept brief.',
  ['Define one tabletop trial question and its limit.','Assign who facilitates and who checks components.','Write two measurable acceptance criteria and stop conditions.','List evidence needed before a larger or public stage.','Make a go/no-go decision from the available record, marking missing evidence.'],
  'The decision can be reviewed and may correctly defer a larger stage.',
  'Do not obtain “approval” by relabeling an unreviewed installation as a prototype.',
  ['What distinguishes stages?','What makes a gate reviewable?','Does passing tabletop tests approve public installation?'],
  ['Scope, loads, users and required review.','Explicit criteria, evidence and responsible roles.','No.'],
  'A bounded trial brief with gate decisions.')

L('Question and baseline',
  'Write a capstone question that can be answered with your available tools.',
  'A useful capstone question defines the design, comparator, metric and conditions. Broad claims such as “tensegrity is more efficient” hide many meanings. A tabletop question can legitimately focus on assembly or angle retention. Quantum Tensegrity belongs to an optional hypothesis track and cannot be validated by a classical tabletop analogy alone.',
  'Question: “Under the same small dummy-panel mass and indoor conditions, does this prism support retain its angle as consistently as a simple frame after three rebuilds?” This names comparator, conditions and repeatability metric without assuming which wins.',
  'Capstone template, existing models or concept drawings, available measuring tools.',
  ['Choose one outcome you can measure.','Name the comparator and common conditions.','Write what would support, weaken or leave the claim unresolved.','Check that the tools can resolve the expected difference.','Define scope and explicitly excluded conclusions.'],
  'The capstone has an answerable question and permits an inconclusive or negative result.',
  'Do not turn an energy-yield question into a mechanics test and then report improved cell efficiency.',
  ['What four elements define the question?','Must a capstone show improvement?','Can a classical prism prove a quantum theory?'],
  ['Design, comparator, metric and conditions.','No; honest negative or inconclusive findings count.','No.'],
  'A predeclared capstone question and evidence criteria.')

L('Prototype and test plan',
  'Prepare comparable trials before observing the result.',
  'A test plan identifies specimens, conditions, instruments, sequence and stopping rules. Repeats help reveal variation but do not erase bias. Alternate or randomize order where conditions may drift. Physical tests use only suitable low-energy tabletop handling, while structural capacity and public-use claims require separate review.',
  'For rebuild repeatability, use three rebuilds of each support and measure angle with the same method. Alternate A,B,A,B,A,B. Record all attempts, including failures. Define handling, joint inspection and how to treat an unreadable angle before beginning.',
  'Two suitable tabletop supports or simulation-only capstone; comparison and experiment templates.',
  ['Assign specimen and build IDs.','Set common dimensions/load conditions and list unmatched factors.','Choose three repeat trials and an alternating sequence.','Specify instruments, resolution and stop conditions.','Have a peer check that the plan could be repeated, then perform only the bounded trial.'],
  'Raw records correspond to the planned sequence and do not quietly omit unsuccessful attempts.',
  'Do not increase loads after seeing encouraging results. A stopped trial is evidence to retain.',
  ['Why alternate order?','Should failed trials be removed?','When are acceptance criteria chosen?'],
  ['To reduce systematic effects of time/order drift.','No; retain and explain them.','Before testing.'],
  'A reviewed test plan and complete trial record.')

L('Results and limitations',
  'Summarize evidence without overstating precision or generality.',
  'Report raw values, a summary and the boundary of your claim. A mean alone hides spread. Explain confounders, stopped trials and measurement limits. Separate numerical verification from physical validation. For an exploratory hypothesis, specify how future observations might falsify it rather than interpreting every result as support.',
  'Synthetic angle errors A=(1,2,3)° and B=(1,1,2)° have means 2° and 1.33° with ranges 2° and 1°. The sample suggests B is more repeatable here, but three trials and instrument resolution do not establish a universal structural advantage.',
  'Trial records, calculator and templates/capstone-report.md.',
  ['Present raw values including stopped or missing trials.','Calculate mean and range for each comparable metric.','Describe instrument resolution and uncontrolled differences.','State a conclusion restricted to tested specimens and conditions.','Name one next experiment that would reduce an important uncertainty.'],
  'The report supports a narrow conclusion and an explicit next step.',
  'Do not claim statistical significance from these small example summaries or present synthetic values as measurements.',
  ['What can a mean hide?','What should limit a conclusion?','What is A’s range?'],
  ['Variation, outliers and failed/missing trials.','Specimens, conditions, methods and uncertainty.','2°.'],
  'A results table, limitations section and next-test proposal.')

L('Demonstration and replication handover',
  'Deliver a portfolio another person can inspect and reproduce.',
  'A handover includes purpose, build details, data, assumptions, inspection and limitations. Demonstrate one meaningful result and invite a teach-back rather than overwhelming the audience. A research claim also needs provenance and a distinction between established mechanics, analogy and hypothesis. A completed course portfolio is not a professional license.',
  'A five-minute demo: one minute question and model, two minutes method/results, one minute tradeoffs, one minute teach-back. Give the listener node labels and instructions, then see whether they can identify C0 or reproduce one calculation.',
  'Completed report, labeled model or digital drawing, replication checklist and consented audience/peer.',
  ['Gather drawings, member schedule, test records, costs and inspection notes.','Prepare a five-minute explanation using the stated structure.','Have a peer reproduce one build step or numerical result.','Record questions and repair missing instructions.','Complete the rubric; choose your next route or optional research module.'],
  'The recipient can locate evidence and reproduce at least one essential task.',
  'Do not label the portfolio as accredited certification or the model as deployment-ready.',
  ['What is replication evidence?','What must accompany a successful demonstration?','Does course completion license structural work?'],
  ['Another person reproduces a specified task/result using the instructions.','Methods, data, assumptions and limitations.','No.'],
  'A replication-ready portfolio and peer handover record.')
